:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font
:toc:
:numbered:

= Summary

= Cartes Hunter

- Au début de votre tour, lancez un d6 de blessure sur un personne joueuse (Utilisation unique).
- Au début de votre tour, lancez un d4 de blessure sur un personne joueuse (Utilisation unique).
- Au début de tour, désignez un personne joueuse, il perd son pouvoir jusqu'à la fin de la partie (Utilisation unique).
- Au début de tour, placez le marqueur de blessures d'un personne joueuse sur 7 (Utilisation unique).
- Pour vous déplacer, vous pouvez normalement les dés ou vous déplacer sur la carte Lieu adjacente.
- A la fin de votre tour, lors de l'activation du pouvoir, vous ne subissez aucune blessure jusqu'au début de votre prochain tour (Utilisation unique).

= Cartes Neutre

- A la mort définitive d'un personnage, vous récupérez tous ses steufs (au lieu d'un seul).
- Lorsque vous infligez 2 blessures de combat à un personnage, vous pouvez lui voler une carte steuf au lieu d'infliger des blessures.
- Récuperer une carte de la défausse de la pile steuf.
- Soignez toutes les blessures.
- Après votre attaque, vous pouvez vous infliger 2 blessures afin d'attaquer de nouveau le même personne joueuse.
- Guérissez de 1 au début de votre tour.

= Cartes Shadow

- Au début de votre tour, vous pouvez infliger 3 blessures à un personne joueuse présent dans le Lieu Porte de l'Outremonde.
- Si vous infligez des blessures de combat, soignez immédiatement 2 de vos blessures.
- Vous pouvez rejouer autant de fois qu'il y a de personnages morts (Utilisation unique).
- Après avoir subi l'attaque d'un personne joueuse, vous pouvez contre-attaquer immédiatement.
- Vous pouvez mentir au carte vision.
- Quand vous attaquer, lancez seulement le dé 4 pour les dgt.
