:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:

= Nombre de cartes par extension

* Nombre de joueurs par extension : 6 joueurs max.

|=======
|Type de cartes |Nombre souhaité minimum |Harry Potter (score de complétion)
|Personnages |18 |17 (8.1)
|Consommables |24 |27 (25.65 - Citation)
|Lieux |10 |19 (17.9 - Citation)
|Equipement : Tête |9 |6 (still TODO)
|Equipement : Corps |9 |2 (still TODO)
|Equipement : Accessoires |18 |20 (still TODO)
|Equipement : Arme |9 |2 (still TODO)
|=======

= Formules de calcul

== Personnages

* Il faut permettre aux joueurs de pouvoir tous jouer dans le même alignement si possible.
** Ce qui fait 6 personnages au maximum dans chaque alignement.
** Ce qui fait un total de 18 personnages, ce qui est amplement suffisant compte tenu de la répartition selon les règles standard de 2 personnages par alignement. ça donne une variété de 2 personnages par règle standard + 4 au choix.
* Au total : 18 personnages.

== Consommables

* Il faut permettre aux joueurs d'avoir deux cartes en main.
** Ce qui fait 12 consommables au maximum dans toutes les mains.
** Ce qui fait un total de 24 consommables, compte tenu d'un multiplicateur de 2 pour le recyclage car les consommables seront beaucoup utilisés.
* Au total : 24 consommables.

== Lieux

* Certains peuvent rester actifs pendant un ou plusieurs tours.
* 10 est un critère arbitraire et cela serait bien d'avoir une meilleure justification.

== Equipement : Tête, Corps, Accessoires et Armes.

* A l'exception des Accessoires, les équipements vont à un emplacement.
** Ce qui fait 6 équipements à procurer pour chaque joueur et à chaque emplacement (12 équipements pour les accessoires, puisque 2 emplacements).
** Ce qui fait un total de 9 équipements par emplacement, compte tenu d'un coefficient de 1.5 pour le recyclage (d'autant plus avec la défausse éternelle du marchand) et 18 pour les accessoires.
* Au total : 9 Tête, 9 Corps, 9 Armes et 18 Accessoires.
