:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:

= Nombre de cartes par extension

* Nombre de joueurs par extension : 6 joueurs max.

|=======
|Type de cartes |Nombre souhaité minimum |Harry Potter (score de complétion)
|Personnages |18 |18 (13.95 - TODO)
|Consommables |24 |24 (24)
|Lieux |18 |18 (18)
|Equipement : Tête |9 |9 (9)
|Equipement : Corps |9 |8 (7.70 - TODO - Effets Cape en écailles de dragon - Need un équipement en plus)
|Equipement : Accessoires |18 |18 (18)
|Equipement : Arme |9 |9 (9)
|=======

= Formules de calcul

== Personnages

* Il faut permettre aux joueurs de pouvoir tous jouer dans le même alignement si possible.
** Ce qui fait 6 personnages au maximum dans chaque alignement.
** Ce qui fait un total de 18 personnages, ce qui est amplement suffisant compte tenu de la répartition selon les règles standard de 2 personnages par alignement. ça donne une variété de 2 personnages par règle standard + 4 au choix.
* Au total : 18 personnages.

== Consommables

* Il faut permettre aux joueurs d'avoir deux cartes en main.
** Ce qui fait 12 consommables au maximum dans toutes les mains.
** Ce qui fait un total de 24 consommables, compte tenu d'un multiplicateur de 2 pour le recyclage car les consommables seront beaucoup utilisés.
* Au total : 24 consommables.

== Lieux

* Certains peuvent rester actifs pendant un ou plusieurs tours.
* 18 lieux, car il y a deux cases Lieux. Et il y a 6 joueurs, en exagérant on peut imaginer que les joueurs font tous les lieux en 2 tours. Il faut donc un peu de rotation possible, mais pas trop pour éviter de composer avec tellement de Lieux que leur apparition paraît unique. [Chiffre à revoir après beta-test.]

== Equipement : Tête, Corps, Accessoires et Armes.

* A l'exception des Accessoires, les équipements vont à un emplacement.
** Ce qui fait 6 équipements à procurer pour chaque joueur et à chaque emplacement (12 équipements pour les accessoires, puisque 2 emplacements).
** Ce qui fait un total de 9 équipements par emplacement, compte tenu d'un coefficient de 1.5 pour le recyclage (d'autant plus avec la défausse éternelle du marchand) et 18 pour les accessoires.
* Au total : 9 Tête, 9 Corps, 9 Armes et 18 Accessoires.
