:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:

= Summary

= Nombre de cartes par collection

* Nombre de joueurs par collection : 6 joueurs max.

|=======
|Type de cartes |Nombre souhaité minimum |Harry Potter |Conte
|Personnages |18 |18 |18
|Consommables |18 |24 |18
|Lieux |12 |18 |12
|Equipement : Tête |9 |9 |9
|Equipement : Corps |9 |9 |9
|Equipement : Accessoires |18 |18 |18
|Equipement : Arme |9 |9 |9
|=======

Cartes renversement, quid ?

= Formules de calcul

== Personnages

* Il faut permettre aux joueurs de pouvoir tous jouer dans le même alignement si possible.
** Ce qui fait 6 personnages au maximum dans chaque alignement.
** Ce qui fait un total de 18 personnages, ce qui est amplement suffisant compte tenu de la répartition selon les règles standard de 2 personnages par alignement. ça donne une variété de 2 personnages par règle standard + 4 au choix.
* Au total : 18 personnages.

== Consommables

* Il faut permettre aux joueurs d'avoir deux cartes en main.
** Ce qui fait 12 consommables au maximum dans toutes les mains.
** Multiplicateur de 1.5 pour le recyclage.
* Au total : 18 consommables.

== Lieux

* Certains peuvent rester actifs pendant un ou plusieurs tours.
* Il faut que le nombre de lieux soit suffisament important pour ne pas tous les visiter en deux tours (on peut imager 3 visites par tour à 6 joueurs), mais pas trop afin que les joueurs en fassent quand même le tour.
* Au total : 12 lieux.

== Equipement : Tête, Corps, Accessoires et Armes.

* A l'exception des Accessoires, les équipements vont à un emplacement.
** Ce qui fait 6 équipements à procurer pour chaque joueur et à chaque emplacement (12 équipements pour les accessoires, puisque 2 emplacements).
** Ce qui fait un total de 9 équipements par emplacement, compte tenu d'un coefficient de 1.5 pour le recyclage (d'autant plus avec la défausse éternelle du marchand) et 18 pour les accessoires.
* Au total : 9 Tête, 9 Corps, 9 Armes et 18 Accessoires.

=== Critère de qualités

* Il y a 4 types de qualités possibles pour les objets. Il faut que cela soit équilibré en terme de valeur apportée à la vente.
* Si possible : il y devrait y avoir autant d'Equipements de chaque catégorie quand ils sont non-légendaires.
* Exemple : j'ai 3 accessoires légendaires dans ma collection, je devrais avoir au minimum 2 objet de chaque catégorie restante (commune, rare, épique), puisque 9 - 3 (nombre de légendaire) = 6 / 3 (le nombre de catégorie restante) = 2