:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:

:equipementsdir: /ressources/images/Harry_Potter/Equipements/

= Equipements

== Accessoires

=== Commune

==== http://harrypotter.wikia.com/wiki/Foe-Glass[Glace à l'ennemi (2 exemplaire) (0.70 - TODO - Effets - Citation)]

** *Détecteur de magie noire (1 charge) :* Le joueur ayant joué avant vous et celui devant joué après vous doivent vous dire à l'oreille s'ils sont d'un alignement contraire au vôtre ou non.
** [Formulation limpide et concise à trouver]
*** Si vous êtes Antagoniste :
**** Si la cible est Protagoniste, elle doit vous dire qu'elle est d'un alignement contraire au vôtre.
**** Si la cible est Antagoniste ou Neutre, elle doit vous dire qu'elle n'est pas d'un alignement contraire au vôtre.
*** Si vous êtes Protagoniste :
**** Si la cible est Antagoniste, elle doit vous dire qu'elle est d'un alignement contraire au vôtre.
**** Si la cible est Protagoniste ou Neutre, elle doit vous dire qu'elle n'est pas d'un alignement contraire au vôtre.
*** Si vous êtes Neutre :
**** Si la cible est Protagoniste ou Antagoniste, elle doit vous dire qu'elle est d'un alignement contraire au vôtre.
**** Si la cible est Neutre, elle doit vous dire qu'elle n'est pas d'un alignement contraire au vôtre.

* Citation :
* Image : {equipementsdir}/Foe_glass.jpg

==== http://harrypotter.wikia.com/wiki/Cleansweep_Eleven[Brossdur 11 (1 exemplaire) (0.95 - TODO - Citation)]

** Vous pouvez vous déplacer d'une case, dans le sens que vous voulez, au lieu de lancer les dés.

* Citation :
* Image : {equipementsdir}/cleansweep_11.jpg

=== Rare

==== http://harrypotter.wikia.com/wiki/Jinx-Off[Gants de démalédiction (1 exemplaire) (0.95 - TODO - Citation)]

* Vous octroie 1 de défense.
* *Ensemble complet de démalédiction :* si vous avez la _Coiffe de démalédiction_, la _Cape de démalédiction_ et les _Gants de démalédiction_, chaque objet vous octroie de 2 défense au lieu de 1. Les effets *Ensemble complet de démalédiction* ne peuvent se cumuler.
* *Equipement fragile :* Si vous passez au Seuil de la Mort avec cet objet équipé, le bonus de défense est annulé. Vous pouvez réparer cet objet en lui octroyant une charge d'utilisation.

* Citation :
* Image : {equipementsdir}/jinx_off.jpg

==== http://harrypotter.wikia.com/wiki/Mrs_Norris[Miss Teigne (1 exemplaire) (0.95 - TODO - Citation)]

** *Regard perçant :* Annule les malus de portée d'un adversaire de combat s'il est à 1 de portée ou moins de vous.
** *Compagnon* : Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (est défaussé définitivement s'il subit 1 blessure).

* Citation :
* Image : {equipementsdir}/miss_teigne.jpg

==== http://harrypotter.wikia.com/wiki/Severus_Snape%27s_copy_of_Advanced_Potion-Making[Livre de potions du Prince de Sang-Mêlé (1 exemplaire) (0.30 - TODO - Effets - Citation)]

** [Vous pouvez sacrifier 2 consommables pour avoir un des effets suivants :]
*** sdds

* Citation :
* Image : {equipementsdir}/advanced_potion_making.jpg

==== http://harrypotter.wikia.com/wiki/Dark_Mark[Marque des Ténèbres (2 Exemplaires) (0.95 - TODO - Citation)]

* Réservé aux Antagonistes
** Ne peut être défaussé, ni vendu.
** Au lieu d'attaquer, vous pouvez activer votre _Marque des Ténèbres_. Jusqu'à votre prochain tour, tous les autres détenteurs d'une _Marque des Ténèbres_ peuvent se téléporter sur votre case au lieu de se déplacer.

* Citation :
* Image : {equipementsdir}/dark_mark.jpg

==== http://harrypotter.wikia.com/wiki/Dumbledore%27s_Army_coin[Pièce de l'Armée de Dumbledore (3 exemplaires) (0.95 - TODO - Citation)]

* Interdit aux Antagonistes.
** Ne peut être vendu.
** Au lieu d'attaquer, vous pouvez activer votre _Pièce de l'Armée de Dumbledore_. Jusqu'à votre prochain tour, tous les autres détenteurs d'une _Pièce de l'Armée de Dumbledore_ peuvent se téléporter sur votre case au lieu de se déplacer.

* Citation :
* Image : {equipementsdir}/dumbledore_army_coin.jpg

==== http://harrypotter.wikia.com/wiki/Nimbus_2001[Nimbus 2001 (1 exemplaire) (0.95 - TODO - Citation)]

** Vous pouvez vous déplacer jusqu'à deux cases, dans le sens que vous voulez, au lieu de lancer les dés.

* Citation :
* Image : {equipementsdir}/nimbus_2001.jpg

==== http://harrypotter.wikia.com/wiki/Buckbeak[Buck (1 exemplaire) (0.95 - TODO - Citation)]

** *Envol :* vous rajoute 1 de portée.
** *Loyauté :* vous ne pouvez bénéficier du bonus de cet équipement pour attaquer un de ses anciens propriétaires.
** *Compagnon :* Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (est défaussé définitivement s'il subit 2 blessures).

* Citation :
* Image : {equipementsdir}/buckbeak.jpg

=== Epique

==== http://harrypotter.wikia.com/wiki/Nagini[Nagini (1 exemplaire) (0.95 - TODO - Citation)]

* *Fidélité extrême à Voldemort :* Réservé aux Antagonistes.
* *Venin :* Les blessures de combat que vous infligez baissent également les Blessures maximums, se limite à [X] effets par cible.
* *Compagnon :* Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (est défaussé définitivement s'il subit 2 blessures).

* Citation :
* Image : {equipementsdir}/thestral.jpg


==== http://harrypotter.wikia.com/wiki/Thestral[Sombral (1 exemplaire) (0.95 - TODO - Citation)]

* *Monture de mauvaise augure :* vous ne pouvez équiper le Sombral que si vous avez été au seuil de la mort au moins une fois.
* *Squelette musclé :* vous permet d'avoir une carte de plus dans votre main.
* *Odeur du sang :* lors de votre phase de déplacement, vous pouvez vous approcher d'une case supplémentaire vers un personnage blessé s'il est à votre portée.
* *Compagnon :* Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (est défaussé définitivement s'il subit 2 blessures).

* Citation :
* Image : {equipementsdir}/thestral.jpg

==== http://harrypotter.wikia.com/wiki/Firebolt_Supreme[Eclair de feu suprême (1 exemplaire) (0.95 - TODO - Citation)]

* Vous pouvez vous déplacer jusqu'à trois cases, dans le sens que vous voulez, au lieu de lancer les dés.
* Vos attaquants ont -1 de portée.

* Citation :
* Image : {equipementsdir}/firebolt.jpg

==== http://harrypotter.wikia.com/wiki/Hand_of_Glory[Main de la gloire (1 exemplaire) (0.65 - TODO - Effets - Citation)]

* L'effet de la _Poudre d'Obscurité Instantanée du Pérou_ est annulé lorsque vous attaquez.
* [effet supplémentaire ?]

* Citation :
* Image : {equipementsdir}/hand_of_glory.jpg

=== Légendaire

==== http://harrypotter.wikia.com/wiki/Resurrection_Stone[Pierre de Résurrection (1 exemplaire) (0.30 - TODO - Effets - Citation)]

* Vous pouvez demander au dernier joueur décédé de regarder toutes les mains des autres joueurs afin de vous en informer. Il n'est pas obligé de dire la vérité.
* Peut être équipé avec la Pierre de Résurrection et la Cape d'Invisibilité.
* Si vous avez équipé dans la partie la Cape d'Invisibilité et la Baguette de Sureau, vous devenez le Maître de la Mort. Mourir ne vous fera perdre aucun point.

* Citation :
* Image : {equipementsdir}/resurrection_stone.jpg

=== Total : 18

== Armes

=== Commune

==== http://harrypotter.wikia.com/wiki/Rubeus_Hagrid%27s_crossbow[Arbalète de Rubeus Hagrid]

* +1 d'attaque.
* +2 de portée.
* [Un tour de cd dû au rechargement ?]

==== http://harrypotter.wikia.com/wiki/Replica_of_the_Sword_of_Gryffindor[dssd]

* ?
* [Peu d'armes existent pr le moment, vraiment pertinent d'en mettre une "inutile" ?]

=== Rare

=== Epique

=== Légendaire

==== http://harrypotter.wikia.com/wiki/Elder_Wand[Baguette de sureau (1 exemplaire) (0.70 - TODO - Effets - Citation)]

* Double tous vos bonus d'attaque , qu'ils soient actifs ou passifs.
* *Maîtrise :* [condition], double tous vos bonus de défense.
* Si vous êtes battu lors d'une attaque, la Baguette de Sureau rentre en possession de votre assaillant.
* Peut-être équipé avec la Pierre de Résurrection et la Cape d'Invisibilité.
* Si vous avez équipé dans la partie la Cape d'Invisibilité et la Pierre de Résurrection, vous devenez le Maître de la Mort. Mourir ne vous fera perdre aucun point.

* Citation :
* Image : {equipementsdir}/elder_wand.jpg

==== http://harrypotter.wikia.com/wiki/Sword_of_Gryffindor[Epée de Godric Griffondor (1 exemplaire) (0.70 - TODO - Effets - Citation)]

* + 1 attaque.
* Cette épée garde ses caractéristiques tout au long de la partie, même si elle change de propriétaire ou qu'elle va dans la défausse.
* A chaque fois que vous attaquez un adversaire, si la différence de dégât en votre faveur est égal ou supérieur à 4, l'arme adverse est brisée et la votre gagne systématiquement ses effets bénéfiques si ceux-ci sont plus puissants que les vôtres (les armes sont défaussées éternellement, placez-les sous la carte de l'Epée).

* Citation :
* Image : {equipementsdir}/godrics_sword.jpg

=== Total : 2

== Corps

=== Commune

===== http://harrypotter.wikia.com/wiki/Shield_Cloak[Manteau bouclier]

* Encaisser une seule attaque ?

=== Rare

==== http://harrypotter.wikia.com/wiki/Jinx-Off[Cape de démalédiction (1 exemplaire) (0.95 - TODO - Citation)]

* Vous octroie 1 de défense.
* *Ensemble complet de démalédiction :* si vous avez la _Coiffe de démalédiction_, la _Cape de démalédiction_ et les _Gants de démalédiction_, chaque objet vous octroie de 2 défense au lieu de 1. Les effets *Ensemble complet de démalédiction* ne peuvent se cumuler.
* *Equipement fragile :* Si vous passez au Seuil de la Mort avec cet objet équipé, le bonus de défense est annulé. Vous pouvez réparer cet objet en lui octroyant une charge d'utilisation.

* Citation :
* Image : {equipementsdir}/jinx_off.jpg

==== http://harrypotter.wikia.com/wiki/Invisibility_cloak[Cape d'Invisibilité standard (1 exemplaire) (0.95 - TODO - Citation)]

* *Invisibilité dégradative (2 charges) :*
** Utilisable uniquement durant votre tour, dure 1 tour.
** On ne peut vous attaquer que si l'on est sur la même case que vous ou à une case de distance. N'interagit pas avec la portée.

* Citation :
* Image : {equipementsdir}/invisbility_cloak_standard.jpg

=== Epique

=== Légendaire

==== http://harrypotter.wikia.com/wiki/Cloak_of_Invisibility[Cape d'Invisibilité (1 exemplaire) (0.80 - TODO - Effets - Citation)]

* [On ne peut vous attaquer que si l'on est sur la même case que vous ou à une case de distance. N'interagit pas avec la portée.]
* [Résister aux effets négatifs ?]
* Peut-être équipé avec la Pierre de Résurrection et la Baguette de Sureau.
* Si vous avez équipé dans la partie la Pierre de Résurrection et la Baguette de Sureau, vous devenez le Maître de la Mort. Mourir ne vous fera perdre aucun point.

* Citation :
* Image : {equipementsdir}/invisbility_cloak.jpg

=== Total : 3

== Tête

=== Commune

==== http://harrypotter.wikia.com/wiki/Spectrespecs[Lorgnospectres (2 exemplaires) (0.95 - TODO - Citation)]

* *Détecteur de Joncheruine :* vous pouvez voir les joncheruines autour de la tête des personnages. Cela ne sert à rien. Les objets _Cape d'Invisibilité standard_ et _Cape d'Invisibilité_ ont leurs effets annulés contre vous.

* Citation :
* Image : {equipementsdir}/spectrespecs.jpg

==== http://harrypotter.wikia.com/wiki/Narcissa_Malfoy%27s_spider_earrings[Narcissa_Malfoy%27s_spider_earrings (1 exemplaire)]

* *Bijou de sang-pur :* cet équipement peut être vendu comme équipement de qualité Epique.

* Citation :
* Image : {equipementsdir}/spider_earrings.jpg

==== http://harrypotter.wikia.com/wiki/Quidditch_helmet[Casque de Quidditch (1 exemplaire)]

* Vous octroie 1 de défense, 1 de défense de plus si vous êtes attaqué au corps-à-corps.

* Image : {equipementsdir}/quidditch_helmet.jpg

=== Rare

==== http://harrypotter.wikia.com/wiki/Luna_Lovegood%27s_lion_hat[Chapeau lion de Luna Lovegood (1 exemplaire) (0.95 - TODO - Citation)]

* Vous octroie 1 de défense.
* *Rugissement effrayant (2 charges d'utilisation) :* les personnages autour de votre case reculent d'une case sans l'activer.

* Citation :
* Image : {equipementsdir}/chapeau_lion.jpg

==== http://harrypotter.wikia.com/wiki/Jinx-Off[Coiffe de démalédiction (1 exemplaire) (0.95 - TODO - Citation)]

* Vous octroie 1 de défense.
* *Ensemble complet de démalédiction :* si vous avez la _Coiffe de démalédiction_, la _Cape de démalédiction_ et les _Gants de démalédiction_, chaque objet vous octroie de 2 défense au lieu de 1. Les effets *Ensemble complet de démalédiction* ne peuvent se cumuler.
* *Equipement fragile :* Si vous passez au Seuil de la Mort avec cet objet équipé, le bonus de défense est annulé. Vous pouvez réparer cet objet en lui octroyant une charge d'utilisation.

* Citation :
* Image : {equipementsdir}/jinx_off.jpg

=== Epique

==== http://harrypotter.wikia.com/wiki/Alastor_Moody%27s_magical_eye[Oeil magique d'Alastor Maugrey (1 exemplaire) (0.95 - TODO - Citation)]

* Pendant votre tour, vous pouvez choisir un joueur, celui-ci devra vous réveler sa main, et uniquement à vous.

* Citation :
* Image : {equipementsdir}/magical_eye_moody.jpg

==== http://harrypotter.wikia.com/wiki/Sorting_Hat[Le Choixpeau magique (1 exemplaire) (0.95 - TODO - Citation)]

* (Réservé aux Protagonistes) Lorsque vous êtes attaqué à 2 Blessures de la mort ou moins, vous pouvez obtenir l'arme Epée de Godric Griffondor, qu'importe la pile dans laquelle elle se trouve et même un autre joueur la possédait déjà.
* *Legilimency chapelière (2 charges d'utilisation) :* Le joueur ciblé doit indiqué son identité et sa quête aux autres joueurs. Il peut lancez les deux dés, s'il fait [5 ou plus], il a le droit de mentir.

* Citation :
* Image : {equipementsdir}/sorting_hat.jpg

=== Légendaire

==== http://harrypotter.wikia.com/wiki/Rowena_Ravenclaw%27s_diadem[Diadème de Rowena Serdaigle (1 exemplaire) (0.95 - TODO - Citation)]

* *Sagesse :* pendant votre tour, vous avez le droit de revenir sur une de vos actions (déplacement, attaque, utilisation d'une compétence, etc.) pour en annuler l'effet et les conséquences. [Vous pourrez recommencer cette action si vous le souhaitez.]

* Citation :
* Image : {equipementsdir}/ravenclaw_diadem.jpg

=== Total : 8

= Ressources

* http://harrypotter.wikia.com/wiki/Peter_Pettigrew's_wand
* http://harrypotter.wikia.com/wiki/Wand_core
* http://harrypotter.wikia.com/wiki/Wand_wood
* http://harrypotter.wikia.com/wiki/Wand
* http://harrypotter.wikia.com/wiki/Wandlore
* http://harrypotter.wikia.com/wiki/Category:Weapons
* http://harrypotter.wikia.com/wiki/Category:Objects

* Faire le tour des animaux qui existent dans l'univers

* http://harrypotter.wikia.com/wiki/Dragon-skin_coat

= Idées

== Conception de baguettes

=== Coeur

===== http://harrypotter.wikia.com/wiki/Dragon_heartstring[Dragon heartstring]

* Classique et très puissant, apprends vite et tend à appartenir au plus puissant.
* More powerfull with Cherry and Chestnut.

==== http://harrypotter.wikia.com/wiki/Phoenix_feather[Plume de phénix]

* Très puissant, mais sélective de son porteur. Apprécie les prises d'initiatives.

==== http://harrypotter.wikia.com/wiki/Unicorn_hair[Unicorn hair]

* Très fiable, ne peut faire des Dark Arts, loyale. Mélancolique.

==== http://harrypotter.wikia.com/wiki/Kneazle[Kneazle]

* pas très puissant

==== http://harrypotter.wikia.com/wiki/Dittany[Dittany]

* Pour se soigner

==== http://harrypotter.wikia.com/wiki/Thunderbird_tail_feather[Thunderbird_tail_feather]

* Peut sentir le danger autour de soi et répondre de soi-même. Difficile à maitriser.

==== http://harrypotter.wikia.com/wiki/Rougarou_hair[Poil de Rougarou]

* Affinité envers les Dark Arts.

==== http://harrypotter.wikia.com/wiki/Horned_Serpent_horn[Corne de Serpent cornu]

* Très puissante, apprécie le Fourchelangue, capable d'émettre en son en présence d'ennemi autour de soi.

=== Bois

==== http://harrypotter.wikia.com/wiki/Acacia[Acacia]

* Un jet pour savoir si cela fonctionne, plus l'on le réussit, plus on maîtrise cet aspect jusqu'à ce que ça n'existe plus.
* Pvr assez puissant
* La maîtrise annulerait de l'alaétoire ? Quelle condition de maîtrise ?

==== http://harrypotter.wikia.com/wiki/Alder[Alder] ou http://harrypotter.wikia.com/wiki/Willow

* Baguette de heal ?

==== http://harrypotter.wikia.com/wiki/Beech[Beech]

* Choix aléatoire de la cible, plein effet si le choix a été aléatoire.

==== http://harrypotter.wikia.com/wiki/Blackthorn[Blackthorn]

* Renforcer le côté belliqueux d'un personnage.
* maîtrise suite à bcp de combats / blessures engagés ?

==== http://harrypotter.wikia.com/wiki/Cherry_(tree)

* A voir ?

==== http://harrypotter.wikia.com/wiki/Chestnut_(tree)[Chestnut]

* Baguette contre les compagnons ?

==== http://harrypotter.wikia.com/wiki/Laurel[Laurel]

* Bonus absent si pour achever un personnage ?

==== http://harrypotter.wikia.com/wiki/Mahogany[Mahogany] ou http://harrypotter.wikia.com/wiki/Rowan[Rowar]

* Fort bonus de déf

==== http://harrypotter.wikia.com/wiki/Maple[Erable]

* Bonus à voir avec les lieux

==== http://harrypotter.wikia.com/wiki/Silver_lime[Silver lime]

* Fort en legilymency, donc peut-être voir la main de l'adversaire qu'on blesse ?

==== http://harrypotter.wikia.com/wiki/Swamp_mayhaw

* Bois classique. Rien de particulier, stat de base.

==== http://harrypotter.wikia.com/wiki/Walnut_(tree)[Walnut]

* Bonus de versatilité, en changeant d'adversaire.

==== http://harrypotter.wikia.com/wiki/Yew[Yew]

* Bonus de létalité

=== Taille, pertinent ?
