:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:

:equipementsdir: /ressources/images/Harry_Potter/Equipements/

= Equipements

== Accessoires

=== Commune

==== http://harrypotter.wikia.com/wiki/Foe-Glass[Glace à l'ennemi (2 exemplaires)]

* *Détecteur de magie noire (1 charge) :* Le joueur ayant joué avant vous et celui devant joué après vous doivent vous dire à l'oreille s'ils sont d'un alignement contraire au vôtre ou non.
** Si vous êtes Antagoniste :
*** Si la cible est Protagoniste, elle doit vous dire qu'elle est d'un alignement contraire au vôtre.
*** Si la cible est Antagoniste ou Neutre, elle doit vous dire qu'elle n'est pas d'un alignement contraire au vôtre.
** Si vous êtes Protagoniste :
*** Si la cible est Antagoniste, elle doit vous dire qu'elle est d'un alignement contraire au vôtre.
*** Si la cible est Protagoniste ou Neutre, elle doit vous dire qu'elle n'est pas d'un alignement contraire au vôtre.
** Si vous êtes Neutre :
*** Si la cible est Protagoniste ou Antagoniste, elle doit vous dire qu'elle est d'un alignement contraire au vôtre.
*** Si la cible est Neutre, elle doit vous dire qu'elle n'est pas d'un alignement contraire au vôtre.

* Citation : _"Tu les vois, là, qui rôdent tout autour ? Je ne risque pas grand-chose tant que je ne vois pas le blanc de leurs yeux."_, Harry Potter et la Coupe de feu, J.K Rowling, 2000.
* Image : {equipementsdir}Foe_glass.jpg

==== http://harrypotter.wikia.com/wiki/Cleansweep_Eleven[Brossdur 11 (1 exemplaire)]

* Lors de votre phase de déplacement, vous pouvez vous déplacer d'une case, dans le sens que vous voulez, au lieu de lancer les dés.

* Image : {equipementsdir}cleansweep_11.jpg

=== Rare

==== http://harrypotter.wikia.com/wiki/Jinx-Off[Gants de démalédiction (1 exemplaire)]

* Vous octroie 1 de défense.
* *Ensemble complet de démalédiction :* si vous avez la _Coiffe de démalédiction_, la _Cape de démalédiction_ et les _Gants de démalédiction_, chaque objet vous octroie de 2 défense au lieu de 1. Les effets *Ensemble complet de démalédiction* ne peuvent se cumuler.
* *Equipement fragile :* Si vous passez au Seuil de la Mort avec cet objet équipé, le bonus de défense est annulé. Vous pouvez réparer cet objet en lui octroyant une charge d'utilisation.

* Image : {equipementsdir}jinx_off.jpg

==== http://harrypotter.wikia.com/wiki/Mrs_Norris[Miss Teigne (1 exemplaire)]

* *Regard perçant :* Annule les malus de portée d'un adversaire de combat s'il est à 1 de portée ou moins de vous.
* *Compagnon* : Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (est défaussé définitivement s'il subit 1 blessure).

* Image : {equipementsdir}miss_teigne.jpg

==== http://harrypotter.wikia.com/wiki/Severus_Snape%27s_copy_of_Advanced_Potion-Making[Livre de potions du Prince de Sang-Mêlé (1 exemplaire) (0.30 - TODO - Effets - Citation)]

* *Fabrication de potions :* sacrifiez 2 consommables pour avoir un effet aléatoire suivants :
** sdds

* Image : {equipementsdir}advanced_potion_making.jpg

==== http://harrypotter.wikia.com/wiki/Dark_Mark[Marque des Ténèbres (2 Exemplaires)]

* Réservé aux Antagonistes
* Ne peut être vendu, ne peut être défaussé si équipé.
* Au lieu d'attaquer, vous pouvez activer votre _Marque des Ténèbres_. Jusqu'à votre prochain tour, tous les autres détenteurs d'une _Marque des Ténèbres_ peuvent se téléporter sur votre case au lieu de se déplacer.

* Citation : _"Je te montre la mienne si tu me montres la tienne."_, Harry Potter et la Coupe de feu, J.K Rowling, 2000.
* Image : {equipementsdir}dark_mark.jpg

==== http://harrypotter.wikia.com/wiki/Dumbledore%27s_Army_coin[Gallion de l'Armée de Dumbledore (3 exemplaires)]

* Interdit aux Antagonistes.
* Ne peut être vendu.
* Au lieu d'attaquer, vous pouvez activer votre _Pièce de l'Armée de Dumbledore_. Jusqu'à votre prochain tour, tous les autres détenteurs d'une _Pièce de l'Armée de Dumbledore_ peuvent se téléporter sur votre case au lieu de se déplacer.

* Image : {equipementsdir}dumbledore_army_coin.jpg

==== http://harrypotter.wikia.com/wiki/Nimbus_2001[Nimbus 2001 (1 exemplaire)]

* Lors de votre phase de déplacement, vous pouvez vous déplacer de deux cases, dans le sens que vous voulez, au lieu de lancer les dés.

* Citation :
* Image : {equipementsdir}nimbus_2001.jpg

==== http://harrypotter.wikia.com/wiki/Buckbeak[Buck (1 exemplaire)]

* *Envol :* vous rajoute 1 de portée.
* *Loyauté :* vous ne pouvez pas bénéficier du bonus de cet équipement pour attaquer un de ses anciens propriétaires.
* *Compagnon :* Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (est défaussé définitivement s'il subit 2 blessures).

* Image : {equipementsdir}buckbeak.jpg

=== Epique

==== http://harrypotter.wikia.com/wiki/Nagini[Nagini (1 exemplaire)]

* *Fidélité extrême à Voldemort :* Réservé aux Antagonistes.
* *Venin :* Les blessures de combat que vous infligez baissent également les Blessures maximums que vous pouvez subir.
* *Compagnon :* Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (est défaussé définitivement s'il subit 2 blessures).

* Citation : _"Nagini, mange."_, Harry Potter et les Reliques de la Mort, J.K Rowling, 2007.
* Image : {equipementsdir}thestral.jpg


==== http://harrypotter.wikia.com/wiki/Thestral[Sombral (1 exemplaire)]

* *Monture de mauvaise augure :* vous ne pouvez équiper le Sombral que si vous avez été au seuil de la mort au moins une fois.
* *Squelette musclé :* vous permet d'avoir une carte de plus dans votre main.
* *Odeur du sang :* lors de votre phase de déplacement, vous pouvez vous approcher d'une case supplémentaire vers un personnage blessé s'il est à votre portée.
* *Compagnon :* Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (est défaussé définitivement s'il subit 2 blessures).

* Citation : _"Ils sont juste un peu... différents."_, Harry Potter et l'Ordre du phénix, J.K Rowling, 2003.
* Image : {equipementsdir}thestral.jpg

==== http://harrypotter.wikia.com/wiki/Firebolt_Supreme[Eclair de feu suprême (1 exemplaire)]

* Lors de votre phase de déplacement, vous pouvez vous déplacer de trois cases, dans le sens que vous voulez, au lieu de lancer les dés.
* Vos attaquants ont -1 de portée lorsqu'ils vous ciblent.

* Citation : _"Gryffondor mène par quatre-vingts points à zéro et regardez un peu les performances de l'Éclair de Feu !"_, Harry Potter et le Prisonnier d'Azkaban, J.K Rowling, 1999.
* Image : {equipementsdir}firebolt.jpg

==== http://harrypotter.wikia.com/wiki/Hand_of_Glory[Main de la gloire (1 exemplaire)]

* *Déverrouillage (3 charges d'utilisation) :* vous pouvez annulez les effets d'un Lieu dont vous seriez la cible.
* Lorsque vous attaquez un autre personnage, la _Poudre d'Obscurité Instantanée du Pérou_ ne pourra lui faire fuir le combat.

* Image : {equipementsdir}hand_of_glory.jpg

=== Légendaire

==== http://harrypotter.wikia.com/wiki/Resurrection_Stone[Pierre de Résurrection (1 exemplaire)]

* Vous pouvez demander au dernier joueur décédé de regarder toutes les mains des autres joueurs afin de vous en informer. Il n'est pas obligé de dire la vérité.
* Peut être équipé avec la _Cape d'Invisibilité_ et _Baguette de Sureau_.
* Si vous avez aussi équipé dans la partie la _Cape d'Invisibilité_ et la _Baguette de Sureau_, vous devenez le Maître de la Mort. Mourir ne vous fera perdre aucun point.

* Citation : _"Si on pouvait faire revenir les morts[...] Mais si on en croit Beedle le Barde, ils n'auraient pas eu envie de revenir."_, Harry Potter et les Reliques de la Mort, J.K Rowling, 2007.
* Image : {equipementsdir}resurrection_stone.jpg

=== Total : 18

== Armes

=== Commune

==== http://harrypotter.wikia.com/wiki/Rubeus_Hagrid%27s_crossbow[Arbalète de Rubeus Hagrid (1 exemplaire)]

* +1 d'attaque.
* +2 de portée.
* *Rechargement :* si vous avez attaqué à distance, nous ne pourrez bénéficier des bonus de cette arme lors de votre attaque le tour prochain.

* Image : {equipementsdir}hagrid_crossbow.jpg

=== Rare

==== Bois d'hêtre, 35,1 centimètres, plume de phénix (1 exemplaire)

* +1 de portée, +1 d'attaque.
* *Initiative :* +1 d'attaque et +1 de défense si vous avez attaqué un autre personnage durant le tour dernier.
* *Favorable à l'indécision :* si vous avez au moins 2 cibles possibles à attaquer, choisissez-en une aléatoirement et gagner un bonus de +1 d'attaque.
* *Maîtrise :* si vous avez bénéficié 4 fois de l'effet _Favorable à l'indécision_ et / ou l'_Initiative_ (les deux se cumulant), votre bonus d'_Initiative_ passe à 2 d'attaque et de défense au lieu de 1, et l'ancienneté de l'attaque peut remonter à 2 tours. Votre bonus de _Favorable à l'indécision_ passe à 2 d'attaque.
* Les conditions de maîtrise ne peuvent être remplies par des actions antérieures à l'acquisition de l'arme. Le bonus de maîtrise n'existe que tant que vous avez l'arme équipée. Cependant, perdre cette arme puis la retrouver plus tard ne fait pas disparaître la maitrise.

* Image : {equipementsdir}wand_hetre.jpg

==== Bois de châtaignier, 27,4 centimètres, crin de Licorne (1 exemplaire)

* +1 de portée, +2 d'attaque et +2 de défense.
* *Spécisme :* bonus de +1 d'attaque et de défense si l'ennemi possède un accessoire avec la compétence _Compagnon_.
* *Endeuillement :* malus de -1 d'attaque et de défense si un autre personnage de votre alignement est décédé pendant la partie.
* *Maîtrise :* après avoir détruit un accessoire adverse disposant de la compétence _Compagnon_, votre bonus de _Spécisme_ passe à 2 d'attaque et de défense au lieu de 1.
* Les conditions de maîtrise ne peuvent être remplies par des actions antérieures à l'acquisition de l'arme. Le bonus de maîtrise n'existe que tant que vous avez l'arme équipée. Cependant, perdre cette arme puis la retrouver plus tard ne fait pas disparaître la maitrise.

* Image : {equipementsdir}wand_chataignier.jpg

==== Bois d'érable, 41,8 centimètres, plume d'oiseau-tonnerre (1 exemplaire)

* +1 de portée.
* *Explorateur :* bonus de +2 d'attaque et de défense si vous êtes sur une case _Lieux_.
* *Vigilance :* bonus de +1 de défense si un personnage de l'alignement adverse est à 1 case de la votre.
* *Maîtrise :* après vous êtes défendu 3 fois avec succès ou après avoir visité 3 _Lieux_ différents, votre bonus d'_Explorateur_ passe à 3 d'attaque et de défense au lieu de 2 et cela fonctionne à une case adjacente de la case _Lieux_. L'effet _Vigilance_ vous permet désormais également de contre-attaquer l'adversaire.
* Les conditions de maîtrise ne peuvent être remplies par des actions antérieures à l'acquisition de l'arme. Le bonus de maîtrise n'existe que tant que vous avez l'arme équipée. Cependant, perdre cette arme puis la retrouver plus tard ne fait pas disparaître la maitrise.

* Image : {equipementsdir}wand_erable.jpg

=== Epique

==== Bois de prunellier, 26 centimètres, poil de Rougarou (1 exemplaire)

* +1 de portée et +2 d'attaque.
* *Belliqueuse :* +1 d'attaque si vous attaquez une cible pour la première fois (lieux comme personnages).
* *Maîtrise :* après avoir blessé au moins la moitié supérieure des autres joueurs toujours en vie, votre bonus de _Belliqueuse_ octroie également un bonus de défense de 2 en vous défendant contre un joueur que vous avez blessé. Vous débloquez aussi l'effet *Furie sanguinaire :* vous avez actuellement +1 d'attaque pour chaque joueur encore en vie que vous avez blessé dans la partie.
* Les conditions de maîtrise ne peuvent être remplies par des actions antérieures à l'acquisition de l'arme. Le bonus de maîtrise n'existe que tant que vous avez l'arme équipée. Cependant, perdre cette arme puis la retrouver plus tard ne fait pas disparaître la maitrise.

* Image : {equipementsdir}wand_prunellier.jpg

==== Bois d'if, 29,1 centimètres, ventricule de dragon (1 exemplaire)

* +1 de portée, +2 d'attaque et +2 de défense.
* *Bourreau :* +1 d'attaque contre les personnages au seuil de la mort.
* *Opportuniste :* lorsque vous êtes vaincu lors d'une attaque par un personnage ayant moins de blessures actuelles que vous, l'arme parvient en sa possession.
* *Maîtrise :* après avoir achevé définitivement un autre personnage, désormais, vos blessures amenant des personnages au seuil de la Mort les tuent directement à la place. Vous débloquez également la compétence *Moissoneur de vie :* tous les deux personnages que vous avez achevé définitivement vous confère +1 d'attaque et de défense (mettez leurs cartes _Personnages_ en dessous de la votre).

* Image : {equipementsdir}wand_if.jpg

==== Bois de tilleul argenté, 21,9 centimètres, corne de Serpent cornu (1 exemplaire)

* +1 de portée, +2 d'attaque et +1 de défense.
* *Affinité envers la Legilimency :* si une attaque à un autre personnage lui inflige des blessures, il doit vous révéler sa main.
* *Détection serpentine :* pendant leur tour, les autres joueurs se déplaçant à une case de vous déclenche les mêmes effets de détection que le _Miroir à l'ennemi_.
* *Maîtrise :* après avoir confondu un autre personnage au _Tribunal magique_ avec succès ou en ayant révélé plus de 6 cartes d'adversaires grâce à l'_Affinité envers la Legilimency_, l'_Affinité envers la Legilimency_ vous permet, selon votre choix, de réveler la carte personnage de l'adversaire ou de lui voler une carte de sa main.

* Image : {equipementsdir}wand_tilleul_argente.jpg

=== Légendaire

==== http://harrypotter.wikia.com/wiki/Elder_Wand[Baguette de sureau (1 exemplaire)]

* +1 de portée, +1 d'attaque et +1 de défense.
* *Duplicateur de puissance :* Double tous vos bonus d'attaque , qu'ils soient actifs ou passifs.
* *Maîtrise :* [si sortez victorieux d'un combat contre tous les autres joueurs de la partie encore en vie (que ce soit en se défendant ou en attaquant)], l'effet _Duplicateur de puissance_ double également tous vos bonus de défense.
* Les conditions de maîtrise ne peuvent être remplies par des actions antérieures à l'acquisition de l'arme. Le bonus de maîtrise n'existe que tant que vous avez l'arme équipée. Cependant, perdre cette arme puis la retrouver plus tard ne fait pas disparaître la maitrise.
* *Allégeance intéressée :* Si vous êtes battu lors d'une attaque, la Baguette de Sureau rentre en possession de votre assaillant.
* Peut être équipé avec la _Pierre de Résurrection_ et la _Cape d'Invisibilité_.
* Si vous avez aussi équipé dans la partie la _Cape d'Invisibilité_ et la _Pierre de Résurrection_, vous devenez le Maître de la Mort. Mourir ne vous fera perdre aucun point.

* Citation : _"[...] les humains ont le don de jeter leur dévolu sur les choses qui, précisément, leur font le plus de mal."_ Harry Potter, J.K Rowling.
* Image : {equipementsdir}elder_wand.jpg

==== http://harrypotter.wikia.com/wiki/Sword_of_Gryffindor[Epée de Godric Griffondor (1 exemplaire)]

* +2 d'attaque et +1 de défense.
* Cette épée garde ses caractéristiques tout au long de la partie, même si elle change de propriétaire ou qu'elle va dans la défausse.
* A chaque fois que vous attaquez un adversaire, si la différence en votre faveur est égal ou supérieur à 4, un équipement adverse est brisé et l'_Epée de Godric Griffondor_ gagne systématiquement ses effets bénéfiques si ceux-ci sont plus puissants que les vôtres (les équipements sont défaussées éternellement, placez-les sous la carte de l'_Epée de Godric Griffondor_).

* Image : {equipementsdir}godrics_sword.jpg

=== Total : 9

== Corps

=== Commune

==== http://harrypotter.wikia.com/wiki/Shield_Cloak[Manteau bouclier (2 exemplaire)]

* *Bouclier contre-tout, mais pas si puissant... :* la prochaine attaque reçu devant vous infliger une blessure ne vous infligera pas une blessure mais détruirera cet objet à la place. Cela ne fonctionne pas lorsque vous êtes au Seuil de la Mort.

* Image : {equipementsdir}shield_cloak.jpg


==== http://harrypotter.wikia.com/wiki/Porcupine_Robe[Robe porc-épine (1 exemplaire)]

* +2 de défense.
* *Qui s'y frotte, s'y pique (3 charges d'utilisation) :* lors d'une défense d'une attaque au corps-à-corps, si le résultat est en votre faveur (l'égalité attaque / défense ne compte pas), vous infligez une blessure à votre assaillant, cela peut le tuer.

* Image : {equipementsdir}porcupine_robe.jpg

=== Rare

==== http://harrypotter.wikia.com/wiki/Jinx-Off[Cape de démalédiction (1 exemplaire)]

* +1 de défense.
* *Ensemble complet de démalédiction :* si vous avez la _Coiffe de démalédiction_, la _Cape de démalédiction_ et les _Gants de démalédiction_, chaque objet vous octroie de 2 défense au lieu de 1. Les effets *Ensemble complet de démalédiction* ne peuvent se cumuler.
* *Equipement fragile :* Si vous passez au Seuil de la Mort avec cet objet équipé, le bonus de défense est annulé. Vous pouvez réparer cet objet en lui octroyant une charge d'utilisation.

* Image : {equipementsdir}jinx_off.jpg

==== http://harrypotter.wikia.com/wiki/Invisibility_cloak[Cape d'Invisibilité standard (1 exemplaire)]

* *Invisibilité dégradative (2 charges) :* Pendant 1 tour, on ne peut vous attaquer que si l'on est sur la même case que vous ou à une case de distance. N'interagit pas avec la portée.

* Image : {equipementsdir}invisbility_cloak_standard.jpg

=== Epique

==== http://harrypotter.wikia.com/wiki/Beautifying_robes[Robe enjolivante (1 exemplaire)]

* *Beauté bluffante :*
** vous pouvez annuler la première fois qu'un autre personnage vous attaque.
** votre premier achat au marchand d'or ne vous coûte que 1.
** votre premier achat au marchand de sang ne vous coûte que 1.

* Image : {equipementsdir}beautifying_robe.jpg

==== http://harrypotter.wikia.com/wiki/Dragon-skin_coat[Cape en écailles de dragon (1 exemplaire) (0.70 - TODO - Effets)]

* +3 de défense.
* [Effet supplémentaire].
* *Extrêmement rare :* peut être vendu comme étant de qualité Légendaire.

* Image : {equipementsdir}dragon_cloak.jpg

=== Légendaire

==== http://harrypotter.wikia.com/wiki/Cloak_of_Invisibility[Cape d'Invisibilité (1 exemplaire)]

* *Invisibilité :* On ne peut vous attaquer que si l'on est sur la même case que vous ou à une case de distance. N'interagit pas avec la portée.
* Vous ne pouvez être la cible d'effets directs vous infligeant des blessures de la part d'autres joueurs (charges d'équipements, consommables, capacités de personnages, etc.).
* Peut être équipé avec la _Pierre de Résurrection_ et la _Baguette de Sureau_.
* Si vous avez aussi équipé dans la partie la _Pierre de Résurrection_ et la _Baguette de Sureau_, vous devenez le Maître de la Mort. Mourir ne vous fera perdre aucun point.

* Image : {equipementsdir}invisbility_cloak.jpg

=== Total : 9

== Tête

=== Commune

==== http://harrypotter.wikia.com/wiki/Spectrespecs[Lorgnospectres (2 exemplaires)]

* *Détecteur de Joncheruine :* vous pouvez voir les joncheruines autour de la tête des personnages. Cela ne sert à rien.

* Image : {equipementsdir}spectrespecs.jpg

==== http://harrypotter.wikia.com/wiki/Narcissa_Malfoy%27s_spider_earrings[Boucles d'oreilles de Narcissa Malefoy (1 exemplaire)]

* *Magnifique bijou :* c'est très beau et ça n'a aucune utilité. Mais, cet équipement peut être vendu comme étant de qualité Epique.

* Image : {equipementsdir}spider_earrings.jpg

==== http://harrypotter.wikia.com/wiki/Quidditch_helmet[Casque de Quidditch (1 exemplaire)]

* +1 de défense, +1 de défense en plus si vous êtes attaqué au corps-à-corps.

* Image : {equipementsdir}quidditch_helmet.jpg

=== Rare

==== http://harrypotter.wikia.com/wiki/Luna_Lovegood%27s_lion_hat[Chapeau lion de Luna Lovegood (1 exemplaire)]

* +1 de défense.
* *Rugissement effrayant (2 charges d'utilisation) :* les personnages autour de votre case reculent d'une case sans l'activer.

* Image : {equipementsdir}chapeau_lion.jpg

==== http://harrypotter.wikia.com/wiki/Jinx-Off[Coiffe de démalédiction (1 exemplaire)]

* +1 de défense.
* *Ensemble complet de démalédiction :* si vous avez la _Coiffe de démalédiction_, la _Cape de démalédiction_ et les _Gants de démalédiction_ équipés en même temps, chaque objet vous octroie de 2 défense au lieu de 1. Les effets d'*Ensemble complet de démalédiction* ne peuvent se cumuler.
* *Equipement fragile :* Si vous passez au Seuil de la Mort avec cet objet équipé, le bonus de défense est annulé. Vous pouvez réparer cet objet en lui octroyant une charge d'utilisation.

* Image : {equipementsdir}jinx_off.jpg

=== Epique

==== http://harrypotter.wikia.com/wiki/Alastor_Moody%27s_magical_eye[Oeil magique d'Alastor Maugrey (1 exemplaire)]

* Pendant votre tour, vous pouvez choisir un joueur, celui-ci devra vous réveler sa main, et uniquement à vous.
* La _Cape d'Invisibilité standard_ et la _Cape d'Invisibilité_ n'ont aucun effets sur vous.

* Image : {equipementsdir}magical_eye_moody.jpg

==== http://harrypotter.wikia.com/wiki/Sorting_Hat[Choixpeau magique (1 exemplaire)]

* *Héritier de Griffondor (Réservé aux Protagonistes) :* Lorsque vous êtes attaqué à 2 Blessures de la mort ou moins, vous pouvez obtenir l'arme _Epée de Godric Griffondor_, qu'importe la pile dans laquelle elle se trouve et même un autre joueur la possédait déjà.
* *Legilimancie chapelière (2 charges d'utilisation) :* Le joueur ciblé doit indiqué son identité et sa quête aux autres joueurs. Il peut lancez les deux dés, s'il fait au moins 5, il aura le droit de mentir.

* Citation : _"Pas à Serpentard ? [...] Tu es sûr ?"_, Harry Potter à l'École des Sorciers, J.K Rowling, 1997.
* Image : {equipementsdir}sorting_hat.jpg

=== Légendaire

==== http://harrypotter.wikia.com/wiki/Rowena_Ravenclaw%27s_diadem[Diadème de Rowena Serdaigle (1 exemplaire)]

* *Sagesse :* pendant votre tour, vous avez le droit de revenir une fois sur une de vos actions (déplacement, attaque, utilisation d'une compétence, etc.) pour en annuler l'effet et les conséquences. Vous pourrez recommencer cette action si vous le souhaitez.

* Image : {equipementsdir}ravenclaw_diadem.jpg

=== Total : 8

= Ressources

* http://harrypotter.wikia.com/wiki/Wand_core
* http://harrypotter.wikia.com/wiki/Wand_wood
* http://harrypotter.wikia.com/wiki/Wand
* http://harrypotter.wikia.com/wiki/Wandlore
* http://harrypotter.wikia.com/wiki/Category:Weapons
* http://harrypotter.wikia.com/wiki/Category:Objects

* Faire le tour des animaux qui existent dans l'univers

* http://harrypotter.wikia.com/wiki/Lizard_Belt

= Idées

==== Elfe de maison

* +2 d'attaque et de défense.
* Peut se tp à une autre case pour déclencher l'effet pour vous (mais absence des bonus).
* Se sacrifiera pour que vous ne soyez pas au seuil de la mort.
* Par contre, un joueur (y compris vous), s'il est le premier à le faire et qu'il est à sa portée, peut lui offrir un équipement de tête ou de corps (celle-ci vient donc en dessous de la carte elfe et sera défaussée en même temps que lui) afin d'en avoir le contrôle.
* Compagnon : meurt s'il subit 1 blessure.
