:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:

:equipementsdir: /ressources/images/Harry_Potter/Equipements/

= Equipements

== Accessoires

=== Commune

==== http://harrypotter.wikia.com/wiki/Foe-Glass[Glace à l'ennemi (2 exemplaire) (0.70 - TODO - Effets - Citation)]

** *Détecteur de magie noire (1 charge) :* Le joueur ayant joué avant vous et celui devant joué après vous doivent vous dire à l'oreille s'ils sont d'un alignement contraire au vôtre ou non.
** [Formulation limpide et concise à trouver]
*** Si vous êtes Antagoniste :
**** Si la cible est Protagoniste, elle doit vous dire qu'elle est d'un alignement contraire au vôtre.
**** Si la cible est Antagoniste ou Neutre, elle doit vous dire qu'elle n'est pas d'un alignement contraire au vôtre.
*** Si vous êtes Protagoniste :
**** Si la cible est Antagoniste, elle doit vous dire qu'elle est d'un alignement contraire au vôtre.
**** Si la cible est Protagoniste ou Neutre, elle doit vous dire qu'elle n'est pas d'un alignement contraire au vôtre.
*** Si vous êtes Neutre :
**** Si la cible est Protagoniste ou Antagoniste, elle doit vous dire qu'elle est d'un alignement contraire au vôtre.
**** Si la cible est Neutre, elle doit vous dire qu'elle n'est pas d'un alignement contraire au vôtre.

* Citation :
* Image : {equipementsdir}/Foe_glass.jpg

==== http://harrypotter.wikia.com/wiki/Cleansweep_Eleven[Brossdur 11 (1 exemplaire) (0.95 - TODO - Citation)]

** Vous pouvez vous déplacer d'une case, dans le sens que vous voulez, au lieu de lancer les dés.

* Citation :
* Image : {equipementsdir}/cleansweep_11.jpg

=== Rare

==== http://harrypotter.wikia.com/wiki/Jinx-Off[Gants de démalédiction (1 exemplaire) (0.95 - TODO - Citation)]

* Vous octroie 1 de défense.
* *Ensemble complet de démalédiction :* si vous avez la _Coiffe de démalédiction_, la _Cape de démalédiction_ et les _Gants de démalédiction_, chaque objet vous octroie de 2 défense au lieu de 1. Les effets *Ensemble complet de démalédiction* ne peuvent se cumuler.
* *Equipement fragile :* Si vous passez au Seuil de la Mort avec cet objet équipé, le bonus de défense est annulé. Vous pouvez réparer cet objet en lui octroyant une charge d'utilisation.

* Citation :
* Image : {equipementsdir}/jinx_off.jpg

==== http://harrypotter.wikia.com/wiki/Mrs_Norris[Miss Teigne (1 exemplaire) (0.95 - TODO - Citation)]

** *Regard perçant :* Annule les malus de portée d'un adversaire de combat s'il est à 1 de portée ou moins de vous.
** *Compagnon* : Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (est défaussé définitivement s'il subit 1 blessure).

* Citation :
* Image : {equipementsdir}/miss_teigne.jpg

==== http://harrypotter.wikia.com/wiki/Severus_Snape%27s_copy_of_Advanced_Potion-Making[Livre de potions du Prince de Sang-Mêlé (1 exemplaire) (0.30 - TODO - Effets - Citation)]

** [Vous pouvez sacrifier 2 consommables pour avoir un des effets suivants :]
*** sdds

* Citation :
* Image : {equipementsdir}/advanced_potion_making.jpg

==== http://harrypotter.wikia.com/wiki/Dark_Mark[Marque des Ténèbres (2 Exemplaires) (0.95 - TODO - Citation)]

* Réservé aux Antagonistes
** Ne peut être défaussé, ni vendu.
** Au lieu d'attaquer, vous pouvez activer votre _Marque des Ténèbres_. Jusqu'à votre prochain tour, tous les autres détenteurs d'une _Marque des Ténèbres_ peuvent se téléporter sur votre case au lieu de se déplacer.

* Citation :
* Image : {equipementsdir}/dark_mark.jpg

==== http://harrypotter.wikia.com/wiki/Dumbledore%27s_Army_coin[Pièce de l'Armée de Dumbledore (3 exemplaires) (0.95 - TODO - Citation)]

* Interdit aux Antagonistes.
** Ne peut être vendu.
** Au lieu d'attaquer, vous pouvez activer votre _Pièce de l'Armée de Dumbledore_. Jusqu'à votre prochain tour, tous les autres détenteurs d'une _Pièce de l'Armée de Dumbledore_ peuvent se téléporter sur votre case au lieu de se déplacer.

* Citation :
* Image : {equipementsdir}/dumbledore_army_coin.jpg

==== http://harrypotter.wikia.com/wiki/Nimbus_2001[Nimbus 2001 (1 exemplaire) (0.95 - TODO - Citation)]

** Vous pouvez vous déplacer jusqu'à deux cases, dans le sens que vous voulez, au lieu de lancer les dés.

* Citation :
* Image : {equipementsdir}/nimbus_2001.jpg

==== http://harrypotter.wikia.com/wiki/Buckbeak[Buck (1 exemplaire) (0.95 - TODO - Citation)]

** *Envol :* vous rajoute 1 de portée.
** *Loyauté :* vous ne pouvez bénéficier du bonus de cet équipement pour attaquer un de ses anciens propriétaires.
** *Compagnon :* Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (est défaussé définitivement s'il subit 2 blessures).

* Citation :
* Image : {equipementsdir}/buckbeak.jpg

=== Epique

==== http://harrypotter.wikia.com/wiki/Nagini[Nagini (1 exemplaire) (0.95 - TODO - Citation)]

* *Fidélité extrême à Voldemort :* Réservé aux Antagonistes.
* *Venin :* Les blessures de combat que vous infligez baissent également les Blessures maximums, se limite à [X] effets par cible.
* *Compagnon :* Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (est défaussé définitivement s'il subit 2 blessures).

* Citation :
* Image : {equipementsdir}/thestral.jpg


==== http://harrypotter.wikia.com/wiki/Thestral[Sombral (1 exemplaire) (0.95 - TODO - Citation)]

* *Monture de mauvaise augure :* vous ne pouvez équiper le Sombral que si vous avez été au seuil de la mort au moins une fois.
* *Squelette musclé :* vous permet d'avoir une carte de plus dans votre main.
* *Odeur du sang :* lors de votre phase de déplacement, vous pouvez vous approcher d'une case supplémentaire vers un personnage blessé s'il est à votre portée.
* *Compagnon :* Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (est défaussé définitivement s'il subit 2 blessures).

* Citation :
* Image : {equipementsdir}/thestral.jpg

==== http://harrypotter.wikia.com/wiki/Firebolt_Supreme[Eclair de feu suprême (1 exemplaire) (0.95 - TODO - Citation)]

* Vous pouvez vous déplacer jusqu'à trois cases, dans le sens que vous voulez, au lieu de lancer les dés.
* Vos attaquants ont -1 de portée.

* Citation :
* Image : {equipementsdir}/firebolt.jpg

==== http://harrypotter.wikia.com/wiki/Hand_of_Glory[Main de la gloire (1 exemplaire) (0.65 - TODO - Effets - Citation)]

* L'effet de la _Poudre d'Obscurité Instantanée du Pérou_ est annulé lorsque vous attaquez.
* [effet supplémentaire ?]

* Citation :
* Image : {equipementsdir}/hand_of_glory.jpg

=== Légendaire

==== http://harrypotter.wikia.com/wiki/Resurrection_Stone[Pierre de Résurrection (1 exemplaire) (0.30 - TODO - Effets - Citation)]

* Vous pouvez demander au dernier joueur décédé de regarder toutes les mains des autres joueurs afin de vous en informer. Il n'est pas obligé de dire la vérité.
* Peut être équipé avec la Pierre de Résurrection et la Cape d'Invisibilité.
* Si vous avez équipé dans la partie la Cape d'Invisibilité et la Baguette de Sureau, vous devenez le Maître de la Mort. Mourir ne vous fera perdre aucun point.

* Citation :
* Image : {equipementsdir}/resurrection_stone.jpg

=== Total : 18

== Armes

=== Commune

==== http://harrypotter.wikia.com/wiki/Rubeus_Hagrid%27s_crossbow[Arbalète de Rubeus Hagrid (0.80 - TODO - Image - Citation)]

* +1 d'attaque.
* +2 de portée.
* *Rechargement :* si vous avez attaquer à distance, nous ne pourrez bénéficier des bonus de cette arme lors de votre attaque le tour prochain.

* Citation :
* Image : {equipementsdir}/elder_wand.jpg

=== Rare

==== [Bois de Beech, coeur de Plume de phénix, Taille (0.60 - TODO - Nom - Effets - Condition - Citation)]

* +1 de portée, +1 d'attaque.
* *Initiative :* +1 d'attaque et +1 de défense si vous avez attaquer un autre personnage durant le tour dernier.
* *Favorable à l'indécision :* si vous avez au moins 2 cibles possibles à attaquer, choisissez-en une aléatoirement et gagner un bonus de +1 d'attaque.
* *Maîtrise :* [condition], votre bonus d'_Initiative_ passe à 2 d'attaque et de défense au lieu de 1, et l'ancienneté de l'attaque peut remonter à 2 tours. Votre bonus de _Favorable à l'indécision_ passe à 2 d'attaque.
* Les conditions de maîtrise ne peuvent être remplies par des actions antérieures à l'acquisition de l'arme. Le bonus de maîtrise n'existe que tant que vous avez l'arme équipée. Cependant, perdre cette arme puis la retrouver plus tard ne fait pas disparaître la maitrise.

* Image : {equipementsdir}/elder_wand.jpg

==== [Bois de Chestnut, crin de Licorne, Taille (0.70 - TODO - Nom -  Effets - Citation)]

* +1 de portée, +1 d'attaque et +1 de défense.
* *[?] :* bonus de +1 d'attaque et de défense si l'ennemi possède un accessoire avec la compétence _Compagnon_.
* *Endeuillement :* malus de -1 d'attaque et de défense si un autre personnage de votre alignement est décédé pendant la partie.
* *Maîtrise :* [après détruit un accessoire adverse disposant de la compétence _Compagnon_], votre bonus de _[?]_ passe à 2 d'attaque et de défense au lieu de 1. [Un autre bonus ?]
* Les conditions de maîtrise ne peuvent être remplies par des actions antérieures à l'acquisition de l'arme. Le bonus de maîtrise n'existe que tant que vous avez l'arme équipée. Cependant, perdre cette arme puis la retrouver plus tard ne fait pas disparaître la maitrise.

* Image : {equipementsdir}/elder_wand.jpg

==== [Bois de Maple, Thunder, Taille (0.70 - TODO - Nom -  Effets - Citation)]

* +1 de portée.
* *Explorateur :* bonus de +2 d'attaque et de défense si vous êtes sur une case _Lieux_.
* *Vigilance :* bonus de +1 de défense si un personnage de l'alignement adverse est à 1 case de la votre.
* *Maîtrise :* [après vous êtes défendu 3 fois avec succès ou après avoir visité 3 _Lieux_ différents], votre bonus d'_Explorateur_ passe à 3 d'attaque et de défense au lieu de 2 et cela fonctionne à une case adjacente de la case _Lieux_. L'effet _Vigilance_ vous permet désormais de contreattaquer l'adversaire [limiter ça contre l'alignement adverse ?].
* Les conditions de maîtrise ne peuvent être remplies par des actions antérieures à l'acquisition de l'arme. Le bonus de maîtrise n'existe que tant que vous avez l'arme équipée. Cependant, perdre cette arme puis la retrouver plus tard ne fait pas disparaître la maitrise.

* Image : {equipementsdir}/elder_wand.jpg

=== Epique

==== [Bois de Blackthorne, coeur de Rougarou de Licorne, Taille (0.40 - TODO - Nom - Effets - Image)]

* +1 de portée et +2 d'attaque.
* *Belliqueuse :* +1 d'attaque si vous avez une cible pour la première fois (lieux comme personnages).
* *Maîtrise :* après avoir blessé au moins la moitié des autres joueurs toujours en vie, votre bonus de _Belliqueuse_ passe à 2 d'attaque au lieu de 1. [Vous disposez désormais d'un bonus de défense de 2 si un joueur que vous avez blessé vous attaque.]
* Les conditions de maîtrise ne peuvent être remplies par des actions antérieures à l'acquisition de l'arme. Le bonus de maîtrise n'existe que tant que vous avez l'arme équipée. Cependant, perdre cette arme puis la retrouver plus tard ne fait pas disparaître la maitrise.

* Image : {equipementsdir}/elder_wand.jpg

==== [Bois de Yew, Dragon heart, Taille (0.40 - TODO - Nom - Effets - Image)]

* +1 de portée, +2 d'attaque et +1 de défense.
* *Bourreau :* +1 d'attaque contre les personnages au seuil de la mort.
* *Opportuniste :* lorsque vous êtes vaincu lors d'une attaque par un personnage ayant moins de blessures actuelles que vous, l'arme parvient en sa possession.
* *Maîtrise :* après avoir achevé définitivement un autre personnage, désormais, vos blessures amenant des personnages au seuil de la Mort les tue directement à la place.

* Image : {equipementsdir}/elder_wand.jpg

==== [Bois de Silver lime,Serpent cornu, Taille (0.40 - TODO - Nom - Effets - Image)]

* +1 de portée, +2 d'attaque et +1 de défense.
* *Affinité envers la Legilimency :* si une attaque à un autre personnage lui inflige des blessures, il doit vous révéler sa main.
* Autre capacité à trouver, allant vers de la détection [effet constant du _Miroir à l'ennemi_ ?].
* *Maîtrise :* après avoir confondu un autre personnage au _Tribunal magique_ avec succès [ou en ayant révélé plus de 6 cartes d'adversaires], [].

* Image : {equipementsdir}/elder_wand.jpg

=== Légendaire

==== http://harrypotter.wikia.com/wiki/Elder_Wand[Baguette de sureau (1 exemplaire) (0.70 - TODO - Effets - Citation)]

* +1 de portée, +1 d'attaque et +1 de défense.
* Double tous vos bonus d'attaque , qu'ils soient actifs ou passifs.
* *Maîtrise :* [condition], double également tous vos bonus de défense.
* Les conditions de maîtrise ne peuvent être remplies par des actions antérieures à l'acquisition de l'arme. Le bonus de maîtrise n'existe que tant que vous avez l'arme équipée. Cependant, perdre cette arme puis la retrouver plus tard ne fait pas disparaître la maitrise.
* Si vous êtes battu lors d'une attaque, la Baguette de Sureau rentre en possession de votre assaillant.
* Peut-être équipé avec la Pierre de Résurrection et la Cape d'Invisibilité.
* Si vous avez équipé dans la partie la Cape d'Invisibilité et la Pierre de Résurrection, vous devenez le Maître de la Mort. Mourir ne vous fera perdre aucun point.

* Citation :
* Image : {equipementsdir}/elder_wand.jpg

==== http://harrypotter.wikia.com/wiki/Sword_of_Gryffindor[Epée de Godric Griffondor (1 exemplaire) (0.70 - TODO - Effets - Citation)]

* +1 d'attaque.
* Cette épée garde ses caractéristiques tout au long de la partie, même si elle change de propriétaire ou qu'elle va dans la défausse.
* A chaque fois que vous attaquez un adversaire, si la différence de dégât en votre faveur est égal ou supérieur à 4, l'arme adverse est brisée et la votre gagne systématiquement ses effets bénéfiques si ceux-ci sont plus puissants que les vôtres (les armes sont défaussées éternellement, placez-les sous la carte de l'Epée).

* Citation :
* Image : {equipementsdir}/godrics_sword.jpg

=== Total : 2

== Corps

=== Commune

===== http://harrypotter.wikia.com/wiki/Shield_Cloak[Manteau bouclier]

* Encaisser une seule attaque ?

=== Rare

==== http://harrypotter.wikia.com/wiki/Jinx-Off[Cape de démalédiction (1 exemplaire) (0.95 - TODO - Citation)]

* Vous octroie 1 de défense.
* *Ensemble complet de démalédiction :* si vous avez la _Coiffe de démalédiction_, la _Cape de démalédiction_ et les _Gants de démalédiction_, chaque objet vous octroie de 2 défense au lieu de 1. Les effets *Ensemble complet de démalédiction* ne peuvent se cumuler.
* *Equipement fragile :* Si vous passez au Seuil de la Mort avec cet objet équipé, le bonus de défense est annulé. Vous pouvez réparer cet objet en lui octroyant une charge d'utilisation.

* Citation :
* Image : {equipementsdir}/jinx_off.jpg

==== http://harrypotter.wikia.com/wiki/Invisibility_cloak[Cape d'Invisibilité standard (1 exemplaire) (0.95 - TODO - Citation)]

* *Invisibilité dégradative (2 charges) :*
** Utilisable uniquement durant votre tour, dure 1 tour.
** On ne peut vous attaquer que si l'on est sur la même case que vous ou à une case de distance. N'interagit pas avec la portée.

* Citation :
* Image : {equipementsdir}/invisbility_cloak_standard.jpg

=== Epique

=== Légendaire

==== http://harrypotter.wikia.com/wiki/Cloak_of_Invisibility[Cape d'Invisibilité (1 exemplaire) (0.80 - TODO - Effets - Citation)]

* [On ne peut vous attaquer que si l'on est sur la même case que vous ou à une case de distance. N'interagit pas avec la portée.]
* [Résister aux effets négatifs ?]
* Peut-être équipé avec la Pierre de Résurrection et la Baguette de Sureau.
* Si vous avez équipé dans la partie la Pierre de Résurrection et la Baguette de Sureau, vous devenez le Maître de la Mort. Mourir ne vous fera perdre aucun point.

* Citation :
* Image : {equipementsdir}/invisbility_cloak.jpg

=== Total : 3

== Tête

=== Commune

==== http://harrypotter.wikia.com/wiki/Spectrespecs[Lorgnospectres (2 exemplaires)]

* *Détecteur de Joncheruine :* vous pouvez voir les joncheruines autour de la tête des personnages. Cela ne sert à rien.

* Image : {equipementsdir}/spectrespecs.jpg

==== http://harrypotter.wikia.com/wiki/Narcissa_Malfoy%27s_spider_earrings[Boucles d'oreilles de Narcissa Malefoy (1 exemplaire)]

* *Magnifique bijou :* c'est très beau et ça n'a aucune utilité. Mais, cet équipement peut être vendu comme étant de qualité Epique.

* Image : {equipementsdir}spider_earrings.jpg

==== http://harrypotter.wikia.com/wiki/Quidditch_helmet[Casque de Quidditch (1 exemplaire) (0.95 - TODO - Citation)]

* +1 de défense, +1 de défense en plus si vous êtes attaqué au corps-à-corps.

* Citation :
* Image : {equipementsdir}quidditch_helmet.jpg

=== Rare

==== http://harrypotter.wikia.com/wiki/Luna_Lovegood%27s_lion_hat[Chapeau lion de Luna Lovegood (1 exemplaire)]

* +1 de défense.
* *Rugissement effrayant (2 charges d'utilisation) :* les personnages autour de votre case reculent d'une case sans l'activer.

* Image : {equipementsdir}chapeau_lion.jpg

==== http://harrypotter.wikia.com/wiki/Jinx-Off[Coiffe de démalédiction (1 exemplaire)]

* +1 de défense.
* *Ensemble complet de démalédiction :* si vous avez la _Coiffe de démalédiction_, la _Cape de démalédiction_ et les _Gants de démalédiction_ équipés en même temps, chaque objet vous octroie de 2 défense au lieu de 1. Les effets d'*Ensemble complet de démalédiction* ne peuvent se cumuler.
* *Equipement fragile :* Si vous passez au Seuil de la Mort avec cet objet équipé, le bonus de défense est annulé. Vous pouvez réparer cet objet en lui octroyant une charge d'utilisation.

* Image : {equipementsdir}jinx_off.jpg

=== Epique

==== http://harrypotter.wikia.com/wiki/Alastor_Moody%27s_magical_eye[Oeil magique d'Alastor Maugrey (1 exemplaire)]

* Pendant votre tour, vous pouvez choisir un joueur, celui-ci devra vous réveler sa main, et uniquement à vous.
* La _Cape d'Invisibilité standard_ et la _Cape d'Invisibilité_ n'ont aucun effets sur vous.

* Image : {equipementsdir}/magical_eye_moody.jpg

==== http://harrypotter.wikia.com/wiki/Sorting_Hat[Choixpeau magique (1 exemplaire)]

* *Héritier de Griffondor (Réservé aux Protagonistes) :* Lorsque vous êtes attaqué à 2 Blessures de la mort ou moins, vous pouvez obtenir l'arme _Epée de Godric Griffondor_, qu'importe la pile dans laquelle elle se trouve et même un autre joueur la possédait déjà.
* *Legilimancie chapelière (2 charges d'utilisation) :* Le joueur ciblé doit indiqué son identité et sa quête aux autres joueurs. Il peut lancez les deux dés, s'il fait au moins 5, il aura le droit de mentir.

* Citation : _"Pas à Serpentard ? [...] Tu es sûr ?"_, Harry Potter à l'École des Sorciers, J.K Rowling, 1997.
* Image : {equipementsdir}sorting_hat.jpg

=== Légendaire

==== http://harrypotter.wikia.com/wiki/Rowena_Ravenclaw%27s_diadem[Diadème de Rowena Serdaigle (1 exemplaire)]

* *Sagesse :* pendant votre tour, vous avez le droit de revenir une fois sur une de vos actions (déplacement, attaque, utilisation d'une compétence, etc.) pour en annuler l'effet et les conséquences. Vous pourrez recommencer cette action si vous le souhaitez.

* Image : {equipementsdir}/ravenclaw_diadem.jpg

=== Total : 8

= Ressources

* http://harrypotter.wikia.com/wiki/Peter_Pettigrew's_wand
* http://harrypotter.wikia.com/wiki/Wand_core
* http://harrypotter.wikia.com/wiki/Wand_wood
* http://harrypotter.wikia.com/wiki/Wand
* http://harrypotter.wikia.com/wiki/Wandlore
* http://harrypotter.wikia.com/wiki/Category:Weapons
* http://harrypotter.wikia.com/wiki/Category:Objects

* Faire le tour des animaux qui existent dans l'univers

* http://harrypotter.wikia.com/wiki/Dragon-skin_coat

= Idées
