* Harry Potter :
** https://fr.wikipedia.org/wiki/Objets_magiques_de_Harry_Potter
** http://harrypotter.wikia.com/wiki/Probity_Probe
** Pierre philosophale ?
** Balais volants ?
** Un autre véhicule ? Magicobus, Poudlard Express, Voiture volante, Portoloin, Moto volante, Tapis Volant
** Retourneur de temps
** Bézoard
** Carte du maraudeur

=== Accessoires (total ?)

===== Commune
* Glace à l'ennemi (3 exemplaire) [A passer en consommable ?]
** Détecteur de magie noire (1 charge) : Le joueur ayant joué avant vous et celui devant joué après vous doivent vous dire à l'oreille s'ils sont d'un alignement contraire au vôtre (il ne se passe rien si vous êtes Neutre ou s'ils le sont).

===== Rare

* Miss Teigne (1 exemplaire)
** Annule les malus de portée d'un adversaire de combat si il est à 1 de portée ou moins de vous.
** Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (meurt s'il subit 1 blessure).

* link:http://harrypotter.wikia.com/wiki/Severus_Snape%27s_copy_of_Advanced_Potion-Making[Livre de potions du Prince de Sang-Mêlé]
** [Vous pouvez sacrifier 2 consommables pour avoir un des effets suivants :]
*** sdds

[]* Marque de Voldemort
** Ne peut être défaussé
** Permettre de TP ?]

===== Epique

* Nagini (1 exemplaire)
** Fidélité extrême à Voldemort : Réservé aux Antagonistes.
** Venin de ? : Les blessures de combat que vous infligez baissent également les PDB maximums.
** Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (meurt s'il subit 2 blessure).

* link:http://harrypotter.wikia.com/wiki/Thestral[Sombral ?]
**

* link:http://harrypotter.wikia.com/wiki/Buckbeak[Buck]
** Loyauté : vous ne pouvez bénéficier du bonus de cet équipement pour attaquer un de ses anciens propriétaires.
** Peut être ciblé par un adversaire pour subir les conséquences d'un combat à votre place (meurt s'il subit 2 blessure).

* Main de la gloire
** [Annule les malus de portée]

===== Légendaire

* Pierre philosophale
** Génération d'un filtre qui "soignerait"
** Obligation d'en boire à un intervalle régulier sinon la mort ou malus

* Pierre de Résurrection (1 exemplaire)
** Vous pouvez communiquer librement avec les personnages décédés lors de la partie.
** Peut-être équipé avec la Pierre de Résurrection et la Cape d'Invisibilité.
** Si vous avez équipé dans la partie la Cape d'Invisibilité et la Baguette de Sureau, vous devenez le Maître de la Mort. Mourir ne vous fera perdre aucun point.

* Retourneur de temps (1 exemplaire)
** Un petit tour : Retour à l'état du prochain tour ?

=== Armes (total ?)

===== Commune

===== Rare

===== Epique

===== Légendaire

* Baguette de sureau
** Si vous êtes battu lors d'une attaque, la Baguette de Sureau rentre en possession de votre assaillant.
** Double tous vos bonus de dégâts, qu'ils soient actifs ou passifs.
** Peut-être équipé avec la Pierre de Résurrection et la Cape d'Invisibilité.
** Si vous avez équipé dans la partie la Cape d'Invisibilité et la Pierre de Résurrection, vous devenez le Maître de la Mort. Mourir ne vous fera perdre aucun point.

* Epée de Godric Griffondor (1 exemplaire, 1 portée)
** Cette épée garde ses caractéristiques tout au long de la partie, même si elle change de propriétaire.
** A chaque fois que vous attaquez un adversaire, si la différence en votre faveur est égal ou supérieur à 4, l'arme adverse est brisée et la votre gagne ses effets bénéfiques si ceux-ci sont plus puissants que les vôtres (les armes sont défaussés éternellement, placez les sous la carte de l'Epée).
** + 1 dégâts.

=== Corps (total ?)

===== Commune

===== Rare

===== Epique

===== Légendaire

* Cape d'Invisibilité
** [On ne peut vous attaquer que si l'on est sur la même case que vous.]
** [Résister aux effets négatifs ?]
** Peut-être équipé avec la Pierre de Résurrection et la Baguette de Sureau.
** Si vous avez équipé dans la partie la Pierre de Résurrection et la Baguette de Sureau, vous devenez le Maître de la Mort. Mourir ne vous fera perdre aucun point.

=== Tête (total ?)

===== Commune

===== Rare

===== Epique
* Oeil magique du professeur
** [Permet de voir ce qui est pioché par les autres joueurs ?]

* Le Choixpeau magique (1 exemplaire)
** (Réservé aux Protagonistes) Lorsque vous êtes attaqués avec 2 PDS ou moins, vous pouvez obtenir l'arme Epée de Godric Griffondor [(retourner la carte)] et ce même si un autre joueur la possédait déjà.
** Legilimency chapelière (1 charge) : Le joueur ciblé doit dire son identité et sa quête à haute voix. Il peut lancez les deux dés, s'il fait [5 ou plus], il a le droit de mentir.
** Illustration
** Citation

===== Légendaire







* http://harrypotter.wikia.com/wiki/Peter_Pettigrew's_wand
* Faire le tour des animaux qui existent dans l'univers
