:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font
:nbTotal: 0
:toc:
:numbered:

= Lieux

== Soins

=== Taverne de la Tête du Sanglier

* Chaque personne déjà révélée ou voulant se reveler peut venir y boire une bière au beurre (soin de 1 Blessure, malus si 2 effets d'Alcool léger) et échanger ou donner des cartes.

=== Hôpital Ste-Mangouste

* Interdit aux Antagonistes
* Chaque personnage au seuil de la mort peut être soigné de 1 blessure.
* Vous pouvez être soigné de 2 blessures.

== Récupération de cartes

=== http://harrypotter.wikia.com/wiki/Madam_Malkin%27s_Robes_for_All_Occasions[Madame Guipure, prêt-à-porter pour mages et sorciers]

* Vous pouvez récupérer la première carte équipement de "Corps" ou "Tête" dans la pile, mélangez la pile après ça.

=== http://harrypotter.wikia.com/wiki/Twilfitt_and_Tattings[Tissard et Brodette]

* Vous pouvez récupérer la première carte équipement de "Corps" ou "Tête" de qualité "Rare" dans la pile, mélangez la pile après ça.

=== Potage cauldron shop

* [Piocher, payer des cartes consommables]

=== Boutique de Fred et Georges

* Achat de friandes aux différents effets

== Equipements

=== http://harrypotter.wikia.com/wiki/Borgin_and_Burkes[Barjow et Beurk]

* Vous pouvez récupérer une charge sur l'équipement de votre choix, 2 charges si vous êtes un Antagoniste.
* Pour deux points d'équipement, vous pouvez acheter la _Main de la gloire_ directement depuis la pile d'Equipement. Mélangez la pile ensuite.

=== http://harrypotter.wikia.com/wiki/Gregorovitch_Zauberst%C3%A4be[Gregorovith Zauberstäbe]

* Vous permet de regagner jusqu'à 2 charges sur l'équipement de votre choix.



== Evènements

=== La Forêt Interdite

* Rencontre aléatoire

=== Azkaban

* Vous désignez un autre personnage que vous à votre portée, si vous le battez lors d'un combat singulier, il sera enfermé en prison (il ne subira pas de blessure du combat).
* Il doit faire un double ou 7 en lançant les dés pour en sortir, sinon, il perds un équipement ou une carte de sa main aléatoirement.
* Lorsque le personnage n'a plus d'équipement ou de cartes en main, il est libéré de prison.

=== Salle de la coupe de feu

* Chaque personnage peut y participer à condition d'être à moins de 3 blessures du seuil de la mort.
* La coupe sélectionne aléatoirement un personnage de chaque alignement disponible.
* Celui qui finit avec le moins de Blessures subies au bout de 3 tours remporte la coupe [(5 points dans le comptage final)], et 3 équipements et 2 consommables.
* Une fois la coupe remportée, défausser définitivement ce lieu.

=== Tribunal magique

* Vous pouvez dénoncer un autre personnage en indiquant ce que vous pensez être sa quête. Le personnage devra indiquer si vous dites vrai ou non, il ne peut mentir.

=== Poudlard Express (Le prisonnier d'Azkaban)

** *Rencontre avec un détraqueur :* en commençant par le personnage qui a découvert ce lieu puis selon l'ordre de jeu, chaque joueur à une case du Lieu doit affronter un détraqueur. Défendez-vous de la même façon qu'un combat ordinaire, si votre défense n'est pas supérieur à 3, vous perdez une carte aléatoirement (de votre main ou de vos équipements).

== Autres

=== La salle sur demande

* Vous permet d'avoir l'effet de la case que vous souhaitez.

=== Banque de Gringotts

* Vous permet de stocker / reprendre jusqu'à deux cartes de votre main.

=== http://harrypotter.wikia.com/wiki/The_Burrow[Le terrier]

* *Doux foyer :* vous ne pouvez attaquer personne et personne ne peut vous attaquer tant que vous vous trouvez dans ce lieu.

* Cohérence du pouvoir avec le lieu ?

=== Chemin de traverse

* En commençant par celui qui a découvert le _Chemin de traverse_, et dans l'ordre de jeu, chaque personnage peut acheter un équipement comme s'il était sur la case marchand d'or.

=== http://harrypotter.wikia.com/wiki/Veil[Le voile]

* Actif pour tous les joueurs jusqu'à la fin de votre prochain tour de jeu.
* Il ne sera pas possible de fouiller ou d'intéragir avec le corps d'un personnage mort.

=== Station de train

* Si vous le voulez, à votre prochain tour, votre déplacement vous mènera directement à la case opposée à la votre sur le plateau.



= Ressources

* http://harrypotter.wikia.com/wiki/Order_of_the_Phoenix
* https://en.wikipedia.org/wiki/Places_in_Harry_Potter
* http://harrypotter.wikia.com/wiki/Ministry_of_Magic
* http://harrypotter.wikia.com/wiki/Malfoy_Manor
* http://harrypotter.wikia.com/wiki/Skirmish_at_Malfoy_Manor
* http://harrypotter.wikia.com/wiki/Study_of_Ancient_Runes
* http://harrypotter.wikia.com/wiki/Fundamental_Laws_of_Magic
* http://harrypotter.wikia.com/wiki/Philosopher%27s_Stone_Chambers
* http://harrypotter.wikia.com/wiki/Mirror_of_Erised

= Idées

=== La cabane hurlante

** [Malus de portée quand on vous attaque dans ce lieu ?]
