:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font
:nbTotal: 0
:toc:
:numbered:

:lieuxdir: /ressources/images/Harry_Potter/Personnages/

= Lieux

== Soins

=== http://harrypotter.wikia.com/wiki/Hog%27s_Head_Inn[Taverne de la Tête du Sanglier]

* Chaque personnage déjà révélée, ou voulant s'y révélant, peut venir y boire une _Bièraubeurre_ (soin de 1 Blessure, malus si 2 effets d'Alcool léger) et échanger / donner des cartes.

* Citation : _"Je crois que l'endroit est un peu... comment dire... un peu louche..."_, Harry Potter et l'Ordre du phénix, J.K Rowling, 2003.
* Image : {lieuxdir}hogshead.jpg

=== http://harrypotter.wikia.com/wiki/St_Mungo%27s_Hospital_for_Magical_Maladies_and_Injuries[Hôpital Ste-Mangouste]

* Interdit aux Antagonistes
* Chaque personnage au seuil de la mort peut être soigné de 1 blessure.
* Vous pouvez être soigné de 2 blessures.

* Citation : _"Des médecins ? Tu veux dire ces Moldus cinglés qui coupent les gens en morceaux ? Non, eux, ce sont des guérisseurs."_, Harry Potter, J.K Rowling.
* Image : {lieuxdir}st_mungo.jpg

== Récupération de cartes

=== http://harrypotter.wikia.com/wiki/Madam_Malkin%27s_Robes_for_All_Occasions[Madame Guipure, prêt-à-porter pour mages et sorciers]

* Vous pouvez récupérer la première carte équipement de "Corps" ou "Tête" dans la pile, mélangez la pile après ça.

* Image : {lieuxdir}madam_malkin.jpg

=== http://harrypotter.wikia.com/wiki/Weasleys%27_Wizard_Wheezes[Boutique de Fred et Georges]

* *Goûteur dévoué :* par sympathie, vous goûtez la nouvelle dragées surprise des frères Weasleys. Lancez les deux dés :
** 2 : piocher une carte retournement.
** 3 : votre prochain jet de dé sera le score minimum possible.
** 4 : subissez une blessure, soignez-vous 2 blessures au début de votre prochaine tour.
** 5 : vous regagnez une charge sur une de vos compétences.
** 6 : jusqu'à que vous subissiez une nouvelle blessure, vous pourrez lancer deux fois les dés et choisir le jet vous intéressant pour vous déplacer.
** 7 : vous goûtez deux nouvelles dragées, quelle gourmandise !

* Citation : _"Vous avez peur de Vous-Savez-Qui ? Craignez plutôt POUSSE-RIKIKI..."_, Harry Potter et le Prince de sang-mêlé, J.K Rowling, 2005.
* Image : {lieuxdir}weasleys_wizard_wheezes.jpg

== Equipements

=== http://harrypotter.wikia.com/wiki/Borgin_and_Burkes[Barjow et Beurk]

* Vous pouvez récupérer une charge sur l'équipement de votre choix, 2 charges si vous êtes un Antagoniste.
* Pour deux points d'équipement, vous pouvez acheter la _Main de la gloire_ directement depuis la pile d'Equipement. Mélangez la pile ensuite.

* Image : {lieuxdir}borgin_and_burkes.jpg

=== http://harrypotter.wikia.com/wiki/Gregorovitch_Zauberst%C3%A4be[Gregorovith Zauberstäbe]

* Vous permet de regagner jusqu'à 1 charge sur l'équipement de votre choix.
* Vous pouvez regagner 1 charge supplémentaire pour 1 points d'équipement, utilisable plusieurs fois sur plusieurs équipements.
* Vous ne pouvez tenter cette action que si vous êtes le premier à le faire : si la _Baguette de Sureau_ n'est pas en possession d'un joueur, vous pouvez tenter d'attaquer Gregorovitch. Si le résultat est supérieur à 5, emparez-vous de l'arme. Les effets de ce Lieu sera annulé pour vous jusqu'à la fin de la partie.

* Image : {lieuxdir}gregorovitch_workshop.jpg

== Evènements

=== http://harrypotter.wikia.com/wiki/Forbidden_Forest[La Forêt Interdite]

* Lancez les dés une rencontre aléatoire :
** *2 - Colonie d'Aragog :* si vous n'êtes pas Aragog vous-même, attaquer à plus de [3] 3 fois. Subissez une blessure ou un équipement, selon votre choix, par échec.
** *3 - Ford Anglia détraquée :* lancez les deux dés, si vous faites moins de 4, vous subissez une blessure. Si vous avez fait 7, la _Ford Anglia_ vous emmène à la case adjacente du Lieu de votre choix.
** *4 - Colonie centaure :* si vous êtes un Antagoniste, attaquer à plus de 5 ou lancer un dé à 3 faces pour fuir. Si le résultat n'est pas 3, vous subissez une blessure, perdez un équipement et une carte de votre main. Si vous êtes Firenze, gagnez un consommable et un équipement.
** *5 - Gibier :* vous pouvez attaquer, si vous faites plus de 2, guérissez-vous d'une blessure.
** *6 - Sentier mal balisé :* relancez les dés pour une autre rencontre aléatoire.
** *7 - Touffu :* lancez les deux dés, si vous faites moins de 6, vous subissez deux blessures et perdez deux équipements. Si vous ne disposez pas d'équipement à perdre, cela se répercute sur vos cartes en main, sinon sur vos points de vie. Vous pouvez en décéder.
* Si vous rencontrez des difficultés, vous pouvez demander de l'aide à un autre personnage à une case de distance de ce lieu. Il peut remplir les conditions de victoire à votre place. Il aura le droit de négocier son aide.

* Citation : _"Il y a des tas de bestioles là-dedans, même des loups-garous d'après ce qu'on m'a dit."_, Harry Potter à l'école des sorciers, J.K Rowling, 1997.
* Image : {lieuxdir}forbidden_forest.jpg

=== http://harrypotter.wikia.com/wiki/Azkaban[Azkaban]

* Vous désignez un autre personnage que vous à votre portée, si vous le battez lors d'un combat singulier, il sera enfermé en prison (il ne subira pas de blessure du combat).
* A son prochain tour, il devra faire un double ou 7 en lançant les dés pour en sortir, sinon, il perds un équipement ou une carte de sa main aléatoirement, et ainsi de suite jusqu'à qu'il n'ait plus d'équipements et de cartes en main. Ensuite, il commencera son tour normalement.

* Citation : _"Ils sont enfermés dans leur propre tête, incapables d'avoir la moindre pensée agréable."_, Harry Potter et le Prisonnier d'Azkaban, J.K Rowling, 1999.
* Image : {lieuxdir}azkaban.jpg

=== http://harrypotter.wikia.com/wiki/Goblet_of_Fire[Salle de la coupe de feu]

* Chaque personnage peut y participer à condition d'être à moins de 3 blessures du seuil de la mort.
* La coupe sélectionne aléatoirement un personnage de chaque alignement disponible, il faut 3 personnages participants minimum.
* Celui qui finit avec le moins de Blessures subies au bout de 3 tours remporte la coupe [(5 points dans le comptage final)], et 3 équipements et 2 consommables.
* Une fois la coupe remportée, défausser définitivement ce lieu.

* Image : {lieuxdir}goblet_of_fire.jpg

=== http://harrypotter.wikia.com/wiki/Council_of_Magical_Law[Tribunal magique]

* Vous pouvez dénoncer un autre personnage en indiquant ce que vous pensez être sa quête. Le personnage devra indiquer si vous dites vrai ou non, il ne peut mentir.

* Citation : _"Barry Croupton Junior !"_, Harry Potter et la Coupe de feu, J.K Rowling, 2000.
* Image : {lieuxdir}council_magical.jpg

=== http://harrypotter.wikia.com/wiki/Forest_of_Dean[Forêt de Dean]

** *Rencontre avec les rafleurs :* en commençant par le personnage qui a découvert ce lieu puis selon l'ordre de jeu, chaque joueur à une case de distance du Lieu doit affronter un groupe de rafleurs. Défendez-vous de la même façon qu'un combat ordinaire, si votre défense n'est pas supérieur à 3, vous perdez une carte aléatoirement (de votre main ou de vos équipements).

* Image : {lieuxdir}forest_of_dean.jpg

=== http://harrypotter.wikia.com/wiki/Knockturn_Alley[L'allée des embrumes]

* *Quartier très malfamé* : Pas de défense possible, vos 3 objets équipés les plus qualitatifs (dans l'ordre décroissant de qualité) vous sont retirés et sont remis dans la pile du marchand d'or.

* Citation : _"C'est un endroit très malfamé. Il ne faut surtout pas que quelqu'un te voie là-bas."_, Harry Potter et la Chambe des Secrets, J.K Rowling, 1998.
* Image : {lieuxdir}knockturn_alley.jpg

== Autres

=== http://harrypotter.wikia.com/wiki/Room_of_Requirement[La salle sur demande]

* Vous permet d'avoir l'effet de la case que vous souhaitez.

* Citation : _"Si vous devez demander, jamais vous ne saurez. Si vous savez, il suffit de demander."_, Harry Potter et les Reliques de la Mort, J.K Rowling, 2007.
* Image : {lieuxdir}room_of_requirement.jpg

=== http://harrypotter.wikia.com/wiki/Gringotts_Wizarding_Bank[Banque de Gringotts]

* Vous permet de stocker / reprendre jusqu'à deux cartes de votre main face cachées.

* Citation : _"Gringotts est l'endroit le plus sûr du monde. À part Poudlard, peut-être."_, Harry Potter à l'école des sorciers, J.K Rowling, 1997.
* Image : {lieuxdir}gringotts.jpg

=== http://harrypotter.wikia.com/wiki/The_Burrow[Le terrier]

* *Doux foyer :* vous ne pouvez attaquer personne et personne ne peut vous attaquer tant que vous vous trouvez dans ce lieu.
* *Madame Weasley, mère au foyer :* Interdit aux Antagonistes, vous êtes soigné d'une blessure.

* Image : {lieuxdir}burrow.jpg

=== http://harrypotter.wikia.com/wiki/Diagon_Alley[Chemin de traverse]

* En commençant par celui qui a découvert le _Chemin de traverse_, et dans l'ordre de jeu, chaque personnage peut acheter des équipements comme s'il était sur la case marchand d'or.

* Image : {lieuxdir}diagon_alley.jpg

=== http://harrypotter.wikia.com/wiki/Veil[Le voile]

* Actif pour tous les joueurs pendant 2 tours de jeu globaux.
* Il ne sera pas possible de fouiller ou d'intéragir avec le corps d'un personnage mort.

* Citation : _"[...] il n'allait pas tarder à réapparaître de l'autre côté... Sirius, pourtant, ne réapparaissait pas."_, Harry Potter et l'Ordre du phénix, J.K Rowling, 2003.
* Image : {lieuxdir}veil.jpg

= Ressources

* http://harrypotter.wikia.com/wiki/Order_of_the_Phoenix
* https://en.wikipedia.org/wiki/Places_in_Harry_Potter
* http://harrypotter.wikia.com/wiki/Ministry_of_Magic
* http://harrypotter.wikia.com/wiki/Malfoy_Manor
* http://harrypotter.wikia.com/wiki/Skirmish_at_Malfoy_Manor
* http://harrypotter.wikia.com/wiki/Study_of_Ancient_Runes
* http://harrypotter.wikia.com/wiki/Fundamental_Laws_of_Magic
* http://harrypotter.wikia.com/wiki/Philosopher%27s_Stone_Chambers
* http://harrypotter.wikia.com/wiki/Mirror_of_Erised
* http://harrypotter.wikia.com/wiki/Gladrags_Wizardwear

= Idées

=== http://harrypotter.wikia.com/wiki/Twilfitt_and_Tattings[Tissard et Brodette (0.95 - TODO - Citation)]

* Vous pouvez récupérer la première carte équipement de "Corps" ou "Tête" de qualité "Rare" dans la pile, mélangez la pile après ça.

* Citation :
* Image : {lieuxdir}twilfitt_and_tattings.jpg

=== http://harrypotter.wikia.com/wiki/King%27s_Cross_Station[Gare de King's Cross (0.95 - TODO - Citation)]

* Si vous le voulez, à votre prochain tour, votre déplacement vous mènera directement à la case opposée à la votre sur le plateau.

* Citation : _"La gare est pleine de Moldus, il fallait s'y attendre."_, (TODO).
* Image : {lieuxdir}king_cross_station.jpg

=== http://harrypotter.wikia.com/wiki/Shrieking_Shack[La cabane hurlante]

** [Malus de portée quand on vous attaque dans ce lieu ?]
