:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:

:personnagesdir: /images/Personnages/

= Personnages

== Antagoniste

=== http://harrypotter.wikia.com/wiki/Tom_Riddle[Tom Jedusor]

  * [red]*5 Blessures*
  * *La prophétie :* accomplir votre _Quête_ ne termine pas la partie si _Harry Potter_ est toujours en vie.
  * *Horcruxe :* tous les _Personnages_ que vous achevez vous permettent de résister à une mort définitive supplémentaire, peut se cumuler plusieurs fois.
  * [underline]*Feudeymon (1 utilisation / partie) :* tous les _Personnages_ subissent 1 blessure, si cela achève un _Personnage_, le sort se relance autant de fois que cela se produit.

  * Citation : _"Il n’y a pas de bien ni de mal, il n’y a que le pouvoir, et ceux qui sont trop faibles pour le rechercher…"_, Harry Potter à l'École des Sorciers, J.K Rowling, 1997.
  * Image : {personnagesdir}Voldemort.jpg

=== http://harrypotter.wikia.com/wiki/Peter_Pettigrew[Peter Pettigrow]

  * [red]*4 Blessures*
  * *Main d'argent :* +2 d'attaque tant que vous n'avez pas d'_Arme_. S'il vous est possible d'achever un _Protagoniste_ après votre déplacement, vous devez le faire, sans quoi vous subissez une _Blessure_.
  * [underline]*Lâcheté sacrificielle :* peut s'infliger une Blessure pour fuir une attaque, ne peut le faire au _SdM_.
  * [underline]*Animagus :* Vous activez / annuler votre transformation en _Queudver_, votre tour est fini.
  * *Queudver :* Au début de votre tour, vous pouvez regarder la carte _Lieux_ la plus proche de vous. Déplacez qu'avec le d4, -2 de portée adverse, vous ne pouvez attaquer d'autres _Personnages_.

  * Citation : _"Ta dévotion n'est rien d'autre que de la couardise. Tu ne serais pas ici si tu avais un autre endroit où aller."_, Harry Potter et la Coupe de Feu, J.K Rowling, 2000.
  * Image : {personnagesdir}peter_pettigrew.jpg

=== http://harrypotter.wikia.com/wiki/Quirinus_Quirrell[Quirinus Quirrell]

  * [red]*5 Blessures*
  * [underline]*Esprit influençable (1 utilisation / partie) :* vous pouvez oublier votre _Quête_ afin de vous consacrer à celle d'un autre _Personnage_, avec son accord. Sa _Quête_ devient également la vôtre. Néanmoins, vous ne gagnez que la moitié des points de cet accomplissement.
  * [underline]*Possession :* vous pouvez accueillir l'esprit d'un _Personnage_ décédé dans votre corps. Il peut toujours accomplir sa _Quête_ et vous la vôtre. Ceci vous inflige 1 _Blessure_ à chaque début de votre tour, tous les 2 tours. Désormais, _Esprit influençable_ vous donne l'intégralité des points d'accomplissement.
  * *"Cessez de vous moquer de moi !" :* gagnez +2 d'attaque et +1 de défense tant que vous êtes le _Personnage_ en vie le plus de blessé de la partie.

  * Citation : _"Vous êtes un peu trop curieux pour vivre bien longtemps, Potter."_, Harry Potter à l'École des Sorciers, J.K Rowling, 1997.
  * Image : {personnagesdir}quirinus_quirell.jpg

=== http://harrypotter.wikia.com/wiki/Dolores_Umbridge[Dolores Ombrage]

    * [red]*4 Blessures*
    * [underline]*Incarcerem (1 utilisation / tous les 3 joueurs dans la partie) :* un autre _Personnage_ ciblé devient _Entravé_ jusqu'au début de son prochain tour.
    * *Corruptible :* les défenseurs peuvent vous payer 3 points d'_Equipements_ pour éviter l'attaque.
    * [underline]*Sous-secrétaire d'État auprès du Ministère de la Magie (1 utilisation / tour) :* A la place de piocher une carte _Retournement_ quand vous le pouvez ou en payant 7 points d'_Equipements_, vous pouvez édicter un _Amendement du Ministère_. Les _Amendement du Ministère_ ne s'appliquent pas à vous. Vous pouvez décider d'abroger un _Amendement du Ministère_ à tout moment.

    ** Sera une carte à part.
    ** *Vase clos :* il est interdit à toutes personnes de communiquer à l'alignement ennemi des informations qui pourraient leur être utiles [à voir ou autre ? interdire d'échange ? - TODO].
    ** *Prohibition :* il est interdit de posséder ou d'utiliser d'un _Consommable_ disposant d'un effet avec _Alcool_ dans son nom. Défaussez-vous-en immédiatement.
    ** *Désarmement :* les _Armes_ de type _Baguettes_ sont *inactives* en combat entre les joueurs.
    ** *L'éducation avant tout :* la _Boutique de Fred et Georges_ est interdite d'accès, l'utilisation de la _Bombabouse_ est interdite, l'équipement ou la possession de _Lorgnospectres_ également.
    ** *Lutte contrebandière :* chaque carte piochée ou échangée (à l'exception de la _Taverne de la Tête du Sanglier_) doit être montrée à _Dolores Ombrage_.
    ** *Pas de Quidditch, pas de balais :* il est interdit de posséder ou d'équiper des _Accessoires_ de type balais. Défaussez-vous-en immédiatement.
    ** *Organisation illégale :* Vous ne pouvez être plus de 2 joueurs sur la même case, si tel devait être le cas, reculez d'une case, autant de fois que nécessaire.

    * Citation : _"J’ai hâte de vous connaître tous et je suis sûre que nous deviendrons vite de très bons amis !"_, Harry Potter et l’Ordre du Phénix, J.K Rowling, 2003.
    * Image : {personnagesdir}dolores_umbridge.jpg

=== http://harrypotter.wikia.com/wiki/Fenrir_Greyback[Fenrir Greyback]

  * [red]*6 Blessures*
  * *Lycanthropie :* Tous les 4 tours, après votre déplacement, vous vous transformez en _Loup-Garou_ jusqu'au début de votre prochain tour.
  * [underline]*Préparation sélène :* Vous pouvez avancer jusqu'à deux cases supplémentaires lors de votre déplacement précédant votre _Lycanthropie_.
  * [*Chef des rafleurs :* lors d'une attaque réussie, vous pouvez voler un objet équipé à votre cible plutôt que lui infliger une blessure - TODO]

  * Citation : _"Tu sais à quel point j’aime les enfants, Dumbledore."_, Harry Potter et le Prince de sang-mêlé, J.K Rowling, 2005.
  * Image : {personnagesdir}fenrir_greyback.jpg

=== http://harrypotter.wikia.com/wiki/Bellatrix_Lestrange[Bellastrix Lestrange]

  * [red]*5 Blessures*
  * *Cruauté :* chaque attaque consécutive envers un personnage vous donne +1 d'attaque, peut se cumuler jusqu'à 2 fois. Changer de cible fait repartir le bonus de zéro.
  * *Duelliste exceptionnelle :* Si vous avez attaqué avec succès au tour précédent, vous gagnez +2 d'attaque, +2 de défense et annuler l'effet d'_Orgueil mal placé_.
  * *Orgueil mal placé :* si vous ne réussissez pas une attaque ou échouer une défense, baisse votre bonus de _Duelliste exceptionnelle_ de 2. Peut se cumuler jusqu'à vous conférer -2 d'attaque et -2 de défense.
  * *Tortionnaire :* Infligez des blessures lors d'une attaque vous octroie une unité de _Sang_.

  * Citation : _"J'ai tué Sirius Black ! J'ai tué Sirius Black ! J'ai tué Sirius Black ! Essaies de m'attraper !"_, Harry Potter et l’Ordre du Phénix, J.K Rowling, 2003.
  * Image : {personnagesdir}bellatrix_lestrange.jpg

== Neutre

=== http://harrypotter.wikia.com/wiki/Griphook[Gripsec]

  * [red]*4 Blessures*
  * *Sadisme :* +1 d'attaque contre un _Personnage_ plus blessé que lui.
  * *Expertise gobeline :* lors d'un achat auprès du _Marchand d'or_, si la valeur de(s) l'objet(s) échangé(s) est en-dessous de la votre, vous pouvez annuler l'échange, l(es)'_Equipement(s)_ retourne(nt) sur le dessus de la pile.
  * *Ancien employé :* vous pouvez retirer vos objets de la _Banque de Gringotts_ sans avoir tirer cette carte _Lieux_. Virtuellement, vous avez 2 emplacements de carte en main supplémentaires.

  * Citation : _"Les gobelins et les elfes ne sont guère accoutumés à la solidarité ou au respect..."_, Harry Potter et les Reliques de la Mort, J.K Rowling, 2007.
  * Image : {personnagesdir}griphook.jpg

=== http://harrypotter.wikia.com/wiki/Aragog[Aragog] :

  * [red]*7 Blessures*
  * *Venin acromantulère :* après une attaque réussie, jusqu'à la fin de son prochain tour, la cible ne se déplacera qu'avec le d3 et ses bonus d'attaque et de défense seront réduits à la moitié inférieure.
  * *Ponte de Mosag :* A tout moment, lorsque vous recevrez un soin excèdentaire (lorsque vous avez 0 blessure subie), vous générez un _Membre de la couvée_.
  * [underline]*Patriache de colonie :* Vous pouvez sacrifier des _Membres de la couvée_ pour modifier le calcul lors d'un combat, 1 _Membre de la couvée_ sacrifié vous rapporte +1 d'attaque ou de défense, au choix.
  * *Cannibalisme opportun :* si vous êtes au _SdM_ avec des _Membres de la couvée_ encore actifs, vous décédez directement.

  * Citation : _"Des humains. [...] Alors, tuez-les. J'étais en train de dormir."_, Harry Potter et la Chambre des Secrets, J.K Rowling, 1998.
  * Image : {personnagesdir}aragog.jpg

=== http://harrypotter.wikia.com/wiki/Gilderoy_Lockhart[Gilderoy Lockhart] :

  * [red]*4 Blessures*
  * [underline]*Brackium Emendo (1 utilisation / 2 tours) :* ciblez un _Personnage_ à votre portée, et lancez les deux dés. Si le résultat est au moins 6, la cible est soigné d'une Nlessure, sinon, son _Arme_ devient inactive pendant 2 tours.
  * *Escroc :* Vous pouvez gagnez par l'accomplissement d'une quête d'un _Personnage_ affecté par votre compétence _Oubliettes_. Vous ne cumulez pas de points supplémentaires si vous accomplissez plusieurs quêtes en même temps grâce à cette compétence.
  * [underline]*Oubliettes :* Pendant votre tour, ciblez un autre _Personnage_, cela ne peut pas être deux fois la même cible consécutivement. Lancez les deux dés.
    ** Si le résultat est 7, la cible ne gagnera pas de points et la partie ne se terminera pas s'il accomplit sa quête. La cible ne pourra plus utiliser aucune de ses _compétences_ de _Personnage_.
    ** Si le résultat est 6, la cible ne gagnera pas de points et la partie ne se terminera pas s'il accomplit sa quête.
    ** Si le résultat est 3, vous ne gagnerez aucun points et la partie ne se terminera pas si vous finissez votre quête ou celle des autres.
    ** Si le résultat est 2, vous ne gagnerez aucun points et la partie ne se terminera pas si vous finissez votre quête ou celle des autres, et vous ne pourrez plus utiliser vos _compétences_.

  * Citation : _"Et si j’avais voulu vous en empêcher, je n’aurais eu aucun mal à le faire."_, Harry Potter et la Chambre des Secrets, J.K Rowling, 1998.
  * Image : {personnagesdir}gilderoy_lockhart.jpg

=== http://harrypotter.wikia.com/wiki/Peeves[Peeves]

* [red]*1 Blessure*
* *Amortel :* vous ne pouvez être tué. Si vous subissez une Blessure alors que vous êtes au _SdM_, vous ne pourrez pas vous déplacer au prochain tour.
* *A peine physique :* -3 d'attaque.
* *Invisibilité :* -2 de portée pour vos attaquants, on ne peut vous cibler directement que ce soit avec un _Consommable_ ou une compétence d'_Arme_ ou de _Personnage_. Attaquer quelqu'un vous annule l'_Invisibilité_ jusqu'à votre prochain tour.
* [underline]*Esprit du chaos (1 action / tour global de jeu) :*
** Si deux joueurs sont à votre portée, vous pouvez échanger jusqu'à 2 cartes de leurs mains et / ou de leurs _Equipements_. Nécessite l'_Invisibilité_.
** Vous pouvez attaquer un joueur pour le pousser, si l'attaque est réussie, il ne subira pas de Blessure et se décalera d'une case en avant sur la case et l'activera.
** Au lieu de piocher un _Consommable_ ou un _Equipement_, vous pouvez regarder les trois prochaines cartes et les reposer dans l'ordre que vous voulez.
** Vous pouvez prendre un _Equipement_ de la défausse et le mettre à la fin de la pile du _Marchand_ de votre choix.
** *(pendant le tour des autres joueurs)* Si vous êtes sur une case entre deux _Personnages_ s'affrontant, vous pouvez prendre le résultat de l'attaque à la place du défenseur. Vous ne pourrez utiliser _Esprit du chaos_ au tour prochain.

* Citation : _"Je dirai quelque chose quand on me dira s’il te plaît. [...] QUELQUE CHOSE ! Ha ! Ha ! Ha ! Je vous avais prévenu."_, Harry Potter à l'école des sorciers, J.K Rowling, 1997.
* Image : {personnagesdir}peeves.jpg

=== http://harrypotter.wikia.com/wiki/Garrick_Ollivander[Garrick_Ollivander]

  * [red]*4 Blessures*
  * *Maître des baguettes :* dès l'équipement, vous débloquer la compétence _Maîtrise_ des _Armes_ de type baguettes.
  * [underline]*Mémoire eidétique (1 utilisation / tour):* une fois qu'une pile de défausse vient remplacer une pile actuelle, vous êtes libre de consulter les 5 premières cartes de cette nouvelle pile.
  * [underline]*Conjureur doué (1 utilisation / 2 tours) :* vous pouvez piocher une carte _Consommable_.

  * Citation : _"La baguette choisit son sorcier."_, Harry Potter à l'école des sorciers, J.K Rowling, 1997.
  * Image : {personnagesdir}garrick_ollivander.jpg

=== http://harrypotter.wikia.com/wiki/Mundungus_Fletcher[Mondungus Fletcher]

  * [red]*4 Blessures*
  * [underline]*Récupérateur (1 utilisation / tour):* au lieu d'attaquer, vous pouvez récupérer la dernière carte dans la défausse des _Consommables_.
  * *Refourgueur :* vos _Consommables_ valent 1 point d'_Equipement_ et peuvent être vendus en tant que tels.
  * [underline]*Réseau d'informateurs intéressés :* Pendant votre tour, vous pouvez sacrifier 2 points d'_Equipement_ pour regarder la carte _Personnage_ ou _Quête_ d'un autre _Personnage_. Peut être fait plusieurs fois par tour.
  * *Négociateur :* pour chaque achat auprès du _Marchand d'or_, vous pouvez lancer les deux dés, si le résultat est supérieur à 4, cela ne vous coutera que 2 points d'équipements.
  * *Couardise :* vous ne pouvez attaquer si vous êtes à une blessure du seuil de la Mort.

  * Citation : _"C’est Mondingus, il a été arrêté et envoyé à Azkaban ! Il s’est fait passer pour un Inferius au cours d’une tentative de cambriolage…"_, Harry Potter et le Prince de sang-mêlé, J.K Rowling, 2005.
  * Image : {personnagesdir}mundungus_fletcher.jpg

== Protagoniste

=== http://harrypotter.wikia.com/wiki/Harry_Potter[Harry Potter]

  * [red]*5 Blessures*
  * *La prophétie :* accomplir votre quête ne termine pas la partie si _Tom Jedusor_ est toujours en vie.
  * [underline]*Accio (1 utilisation / 2 tours):* Pendant votre tour, nommez une carte de la pile _Consommable_ ou _Equipement_, si celle-ci se trouve dans les 3 prochaines cartes, récupérez-la. Puis, placez les cartes révélées sous le dessous de la pile.
  * [underline]*Expelliarmus (1 utilisation / 2 joueurs dans la partie) :* lors d'un combat, toutes les _Armes_ équipées de l'adversaire sont inactives avant le calcul. Si le résultat du combat est en la faveur d'_Harry Potter_, toutes les _Armes_ équipées de l'adversaire lui reviennent.

  * Citation : _"Je suis un... quoi ?"_, Harry Potter à l'école des sorciers, J.K Rowling, 1997.
  * Image : {personnagesdir}harry_potter.jpg

=== http://harrypotter.wikia.com/wiki/Severus_Snape[Severus Rogue]

  * [red]*5 Blessures*
  * *Agent double :* peut se faire passer pour un Antagoniste tout le long de la partie (comme avec l'effet de la _Glace à l'ennemi_ par exemple) et utiliser ce qui leur est exclusif, ne nécessite pas de se réveler.
  * [underline]*Sectum sempra (1 utilisation / 2 tours) :* au lieu d'attaquer directement une cible à votre portée, vous lui infliger 1 blessure puis 1 blessure au début de son prochain tour. [meilleure idée, plus gros cd ?]
  * [underline]*Maître des potions (1 utilisation / tour):* défaussez 2 _Consommables_ pour concoter une potion et l'administrer à un _Personnage_ à votre portée. Si la cible n'est pas consentante, vous pouvez l'attaquer et lui infliger l'effet de la potion à la place de la Blessure.
  ** http://harrypotter.wikia.com/wiki/Veritaserum[*Veritaserum :*] Posez 3 questions à la cible, les réponses ne pourront être des mensonges.
  ** http://harrypotter.wikia.com/wiki/Blood-Replenishing_Potion[*Potion de Régénération sanguine :*] La cible retourne au nombre de Blessures qui était le sien à la fin de son tour précédent.
  ** http://harrypotter.wikia.com/wiki/Weakness_Potion[*Potion_affaiblissante :*] La cible a son attaque et sa défense divisé par 2 (bonus y compris), arrondi à la moitié inférieure, jusqu'au prochain tour de _Severus Rogue_.
  ** http://harrypotter.wikia.com/wiki/Wolfsbane_Potion[*Potion Tue-loup :*] La cible sous l'effet de _Loup-garou_ n'est pas obligé d'attaquer, dure jusqu'à la fin de son prochain tour.
  ** http://harrypotter.wikia.com/wiki/Alihotsy_Draught[*Goutte désopilante :*] La cible devra attaquer le _Personnage_ le plus proche, sinon elle s'inflige elle-même 1 Blessure, dure jusqu'au début de son prochain tour.
  ** http://harrypotter.wikia.com/wiki/Bulgeye_Potion[*Potion bomboeil :*] La cible reçoit un malus de -2 de portée jusqu'au début de son prochain tour.
  ** http://harrypotter.wikia.com/wiki/Armadillo_Bile_Mixture[*Mixture de bile de tatou :*] Un des _Equipements_ choisi de la cible est défaussée éternellement.

  * Citation : _"A jamais."_, Harry Potter et les Reliques de la Mort, J.K Rowling, 2007.
  * Image : {personnagesdir}severus_rogue.jpg

=== http://harrypotter.wikia.com/wiki/Firenze[Firenze]

  * [red]*5 Blessures*
  * [underline]*Astrologie :* Au début de votre tour, vous pouvez regarder les deux carte _Lieux_.
  * *Habitué des lieux :* Vous pouvez choisir la rencontre que vous faites dans le lieu _La Forêt Interdite_.
  * [underline]*Monture :* Si vous le voulez, vous pouvez proposez à un joueur de déplacer son _Personnage_ en même temps que le votre. Son déplacement n'activera aucune case. [récupérer le mec sur le passage]
  * *Corps de centaure :* +1 d'attaque et +1 de défense. Vous pouvez vous déplacer d'une case supplémentaire lors de votre déplacement.

  * Citation : _"Il arrive qu'on se trompe en lisant le destin dans les planètes. Même les centaures."_, Harry Potter, J.K Rowling.
  * Image : {personnagesdir}firenze.jpg

=== http://harrypotter.wikia.com/wiki/Remus_Lupin[Remus Lupin]

  * [red]*4 Blessures*
  * *Lycanthropie :* Tous les 4 tours, après votre déplacement, vous vous transformez en _Loup-Garou_ jusqu'au début de votre prochain tour.
  * *Duelliste talentueux... :* Si vous avez attaqué avec succès au tour précédent, vous gagnez +1 d'attaque et +1 de défense, peut être cumulé 2 fois.
  * *...nécessitant de l'entretien. :* Si vous n'avez pas attaqué avec succès pendant les 2 derniers tours, vous perdez vos effets de Duelliste talentueux.

  * *Citation :* _"C'est de la force des convictions que dépend la réussite, pas du nombre de partisan."_, Harry Potter et les Reliques de la Mort, J.K Rowling, 2007.
  * Image : {personnagesdir}remus_lupin.jpg

=== http://harrypotter.wikia.com/wiki/Luna_Lovegood[Luna Lovegood]

  * [red]*4 Blessures*
  * *Accoutrement loufoque :* vous pouvez équiper jusqu'à deux objets de _Tête_ et de _Corps_.
  * *Magizoologiste (Pas de raison que cela lui soit propre) :* les _Accessoires_ des autres _Personnages_ ayant la capacité _Compagnon_ ne vous font aucun effet. [Autre compétence ?]
  * Si vous révelez votre identité dès le premier tour, équipez vous directement du _Chapeau lion de Luna Lovegood_ et des _Lorgnospectres_ qu'importe la pile dans laquelle ils se trouvent.

  * Citation : _"Ne t’inquiète pas, tu es aussi sain d’esprit que moi."_, Harry Potter et l’Ordre du Phénix, J.K Rowling, 2003.
  * Image : {personnagesdir}luna_lovegood.jpg

=== http://harrypotter.wikia.com/wiki/Alastor_Moody[Alastor Maugrey]

  * [red]*6 Blessures*
  * [underline]*Jambe de bois détachable :* dorénavant, vos prochains déplacements se feront uniquement avec le d4. Vous confère la capacité _Jambe de bois rattachable_.
  * [underline]*Jambe de bois rattachable :* passez votre déplacement, dorénavant, vos déplacements se feront uniquement avec les deux dés. Vous confère la capacité _Jambe de bois détachable_.
  * *Paranoïa :* +1 de défense contre les ennemis non révélés. Vous ne pouvez recevoir en échange que des cartes qui vous soient revélées (fonctionne avec l'_Oeil magique d'Alastor Maugrey_).
  * *Auror d'exception :* +2 d'attaque et de défense face aux _Antagonistes_.
  * Si vous révelez votre identité dès le premier tour, équipez vous directement de l'_Oeil magique d'Alastor Maugrey_, qu'importe la pile dans laquelle il se trouve.

  * Citation : _"Pour ceux qui n'ont jamais bu de Polynectar, je vous préviens, on dirait de la pisse de gobelin."_, Harry Potter et les Reliques de la Mort, J.K Rowling, 2007.
  * Image : {personnagesdir}alastor_moody.jpg

= Idées

* Norbert Dragoneau (Protagoniste)
* http://harrypotter.wikia.com/wiki/Neville_Longbottom (Protagoniste)
* link:http://harrypotter.wikia.com/wiki/Ghost[Certains des fantômes de Poudlard ?]
* http://harrypotter.wikia.com/wiki/Mykew_Gregorovitch
* http://harrypotter.wikia.com/wiki/Rosmerta
* http://harrypotter.wikia.com/wiki/Death_Eaters
* http://harrypotter.wikia.com/wiki/Muggle
* http://harrypotter.wikia.com/wiki/Golgomath
* http://harrypotter.wikia.com/wiki/Rita_Skeeter
* http://harrypotter.wikia.com/wiki/Antonin_Dolohov
* http://harrypotter.wikia.com/wiki/Molly_Weasley
* http://harrypotter.wikia.com/wiki/Horace_Slughorn
* https://en.wikipedia.org/wiki/Harry_Potter_and_the_Cursed_Child
* http://harrypotter.wikia.com/wiki/Muriel
* http://harrypotter.wikia.com/wiki/Peverell_family
* http://harrypotter.wikia.com/wiki/Dobby
* http://harrypotter.wikia.com/wiki/Kreacher
* http://harrypotter.wikia.com/wiki/Viktor_Krum
* https://fr.wikipedia.org/wiki/Liste_des_personnages_du_monde_des_sorciers_de_J._K._Rowling
* http://harrypotter.wikia.com/wiki/Newton_Scamander
* http://harrypotter.wikia.com/wiki/Bartemius_Crouch_Junior

* http://harrypotter.wikia.com/wiki/Educational_Decree
* http://harrypotter.wikia.com/wiki/Unbreakable_Vow
* Delphini
* Lucius Malfoy ?
* Gellert Grindelwald

* Pour Rogue :
** http://harrypotter.wikia.com/wiki/Draught_of_Living_Death[*Philtre de Mort Vivante :*] La cible est étourdie jusqu'à la fin de son prochain tour. Elle ne peut se déplacer, utiliser une compétence active, attaquer ou se défendre.

* http://harrypotter.wikia.com/wiki/List_of_potions
* http://harrypotter.wikia.com/wiki/Antidote
