:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:

:consommablesdir: /images/Consommables/

= Consommables

== Soins

=== http://harrypotter.wikia.com/wiki/Blishen%27s_Firewhisky[Whisky Pur Feu Blishen (3 exemplaires)]

* Utilisable à tout moment.
** Soignez-vous immédiatement de 1 Blessure.
** +1 de défense jusqu'au début de votre prochain tour.
** *Alcool fort (1 tour) :* Vous ne pourrez faire une action vous conférant l'effet *Alcool fort*.

* Image : {consommablesdir}fire_whisky.jpg

=== http://harrypotter.wikia.com/wiki/Butterbeer[Bièraubeurre (4 exemplaires)]

* Utilisable à tout moment.
** Soignez-vous immédiatement 1 blessure.
** *Alcool léger (1 tour) :* Si vous cumulez plus de 2 effets d'*Alcool léger*, votre prochain déplacement se fera avec le d4.

* Citation : _"Pas de plus grand bonheur que la Bièraubeurre !"_, Publicité pour la Bièraubeurre
* Image : {consommablesdir}butterbeer.jpg

=== http://harrypotter.wikia.com/wiki/Unicorn_blood[Sang de licorne (2 exemplaire)]

* Utilisable à tout moment
** Vous pouvez échapper à la mort une fois, jusqu'à votre prochain tour.
** *Maudit (jusqu'à la fin de la partie) :* vous ne pourrez plus vous déplacer et attaquer dans le même tour, cela sera l'un ou l'autre.
** Vous ne pourrez consommer un autre Sang de licorne tout du long de la partie.

* Citation : _"Le sang de licorne permet de survivre, même si on est sur le point de mourir, mais à un prix terrible."_, Harry Potter à l'école des sorciers, J.K Rowling, 1997.
* Image : {consommablesdir}unicorn_blood.jpg

== Déplacement

=== http://harrypotter.wikia.com/wiki/Floo_Powder[Poudre de cheminette (3 exemplaires)]

* Utilisable lors de votre déplacement.
** Rendez vous sur la case de votre choix, si vous énoncez mal le nom, décalez-vous aléatoirement d'une case de la destination.

* Citation : _"CHEMIN DE TRAVERS !"_, Harry Potter et la Chambe des Secrets, J.K Rowling, 1998.
* Image : {consommablesdir}floo_powder.jpg

=== http://harrypotter.wikia.com/wiki/Vanishing_Cabinet[Armoire à disparaître (2 exemplaires)]

* Utilisable durant votre tour.
** Placez cette carte au-dessous de votre case actuelle.
** Quand les deux _Armoire à disparaître_ sont placées, les joueurs peuvent les utiliser lorsqu'ils arrivent sur la case en question afin de se rendre à l'autre l'_Armoire à disparaître_, activant la case de cette dernière uniquement.

* Image : {consommablesdir}vanishing_cabinet.jpg

== Protection

=== http://harrypotter.wikia.com/wiki/Peruvian_Instant_Darkness_Powder[Poudre d'Obscurité Instantanée du Pérou (2 exemplaires)]

* Utilisable à tout moment.
** Vous permets de fuir une attaque.

* Citation : _"On a tout essayé, Lumos, Incendio. Pas moyen d'obtenir la moindre lueur."_, Harry Potter et le Prince de sang-mêlé, J.K Rowling, 2005.
* Image : {consommablesdir}peruvian_powder_darkness.jpg

=== http://harrypotter.wikia.com/wiki/Dungbomb[Bombabouse (2 exemplaires)]

* Utilisable avant le déplacement des autres joueurs.
** Votre case devient inaccessible aux autres joueurs jusqu'à votre prochain tour. Ils reculent d'une case au lieu de se poser dessus.

* Image : {consommablesdir}dungbomb.jpg

== Autres

=== http://harrypotter.wikia.com/wiki/Felix_Felicis[Potion de Felix Felicis (1 exemplaires)]

* Utilisable à tout moment
** Jusqu'à votre prochain tour, votre prochain tirage de dé atteindra la valeur maximale.

* Citation : _"[...] on s'aperçoit que tout ce qu'on entreprend est couronné de succès... en tout cas jusqu'à ce que ses effets se dissipent."_, Harry Potter et le Prince de sang-mêlé, J.K Rowling, 2005.
* Image : {consommablesdir}felix_felicis.jpg
* Catégorie : Influence du hasard

=== http://harrypotter.wikia.com/wiki/Amortentia[Amortentia (1 exemplaire)]

* Utilisable durant votre tour
** Ciblez un autre _Personnage_, il tombe fou amoureux de vous pendant 2 tours.
** Si vous mourrez, il mourra définitivement aussi. Son cadavre sera inexploitable.
** L'effet peut-être annulé à l'aide d'une _Potion de haine_ (l'un ne remplace pas l'autre).

* Citation : _"Non, elle produit simplement une forte attirance ou une obsession."_, Harry Potter et le Prince de sang-mêlé, J.K Rowling, 2005.
* Image : {consommablesdir}amortentia.jpg

=== http://harrypotter.wikia.com/wiki/Hate_Potion[Potion de haine (2 exemplaires)]

* Utilisable durant votre tour
** Pendant 2 tours, vous pouvez attaquer deux fois par tour le _Personnage_ désigné.
** L'effet peut-être annulé à l'aide de l'_Amortentia_ (l'un ne remplace pas l'autre).

* Image : {consommablesdir}hate_potion.jpg
* Catégorie : Attaque

=== http://harrypotter.wikia.com/wiki/Nose-Biting_Teacup[Tasse à thé mordeuse (2 exemplaires)]

* Utilisable à tout moment
** Le _Consommable_ utilisé par la cible devant soigner des blessures, infligera 1 Blessure à la place et en annulera les effets.
** Cela ne peut achever un joueur.

* Image : {consommablesdir}nose_biting_teacup.jpg
* Catégorie : Attaque / Contre

== Ressources

* https://en.wikipedia.org/wiki/Magic_in_Harry_Potter
* http://harrypotter.wikia.com/wiki/Wizard%27s_Brew
* http://harrypotter.wikia.com/wiki/Bell_jar
* http://harrypotter.wikia.com/wiki/Death
* http://harrypotter.wikia.com/wiki/Verdimillious_Charm
* https://fr.wikipedia.org/wiki/Objets_magiques_de_Harry_Potter
* http://harrypotter.wikia.com/wiki/Dark_Arts
* http://harrypotter.wikia.com/wiki/Potion

== Idées

* Un autre véhicule ? Magicobus, Poudlard Express, Voiture volante, Portoloin, Moto volante, Tapis Volant
* Bézoard

* Le polynectar pour avoir l'alignement d'un autre
