:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:

:imagesdir: /Harry_Potter/Images/
:personnagesdir: /ressources/images/Harry_Potter/Personnages/

= Exemple carte grand format

[cols="1%, 83%, 15%, 1%"]
[width="55%"]
|=======================
1.6+|{set:cellbgcolor:red} 2+| 1.6+|{set:cellbgcolor:red}
2+^|{set:cellbgcolor:none}Peter Pettigrow
2+^.^|{set:cellbgcolor:none} [small]#Mon image#
<.^|[small]#Personnage : Antagoniste# >.^|[small]#4 blessures#
2+a|
[small]
* *Main d'argent :* +2 d'attaque tant que vous n'avez pas d'_Arme_. S'il vous est possible d'achever un _Protagoniste_ après votre déplacement, vous devez le faire, sans quoi vous subissez une _Blessure_.
* [underline]*Lâcheté sacrificielle :* peut s'infliger une Blessure pour fuir une attaque, ne peut le faire au _SdM_.
* [underline]*Animagus :* Vous activez / annuler votre transformation en *Queudver*, votre tour est fini.
* *Queudver :* Au début de votre tour, vous pouvez regarder la carte _Lieux_ la plus proche de vous. Déplacez qu'avec le d4, -2 de portée adverse, vous ne pouvez attaquer d'autres _Personnages_.
2+|{set:cellbgcolor:red}
|=======================
{set:cellbgcolor:none}

= Quelles informations doivent être affichées et comment ?

* Il faut que la taille des encadrés reste la même peu importe le style de carte.

* Le nom de la carte en titre, en haut et encadré.
* Le type de la carte (Consommable, personnage, etc.), cela peut être indiqué avec la couleur [voire une indication en bas de carte déconseillé pour la gestion de l'espace] ?
* Ce que la carte est censé faire
* Une illustration
* (Optionnel, si place disponible) Une citation
* Son extension

* Pour les équipements :
** L'emplacement (dans la catégorie de carte)
** La rareté (dans la catégorie de carte)

* Pour les personnages :
** L'alignement  (dans la catégorie de carte)
** Le nombre de blessures encaissables
