Avancer de cases serait avancer de "Pages" en pages dans le jeu.

- D3 et D4 avec un design spécifique ? Y réfléchir.

- Autre nom que point de santé ?

Case "Marchand" :
- Cela permet de troc des équipements contre ceux en stock du marchand.
- Le paiement se fait visiblement de tous, l'équipement reçu en revanche est face cachée et seul l'acheteur le connait.
- Les légendaires ne peuvent pas être troqués. Les autres équipements troqués auprès du marchand sont défaussés définitivement.
- Un nombre fixe d'équipement (Nombre d'équipements = Nombre de joueurs x 2) mais de rareté aléatoire.
- Prix fixe à [2]

Case "Marchand de sang" :
- Même mécanisme que la case "Marchand".
- Le prix fixe serait de 2 PDV.

- Case "Vol (dans la main)" :
- On désigne un joueur, celui-ci présente ses cartes face cachées, puis on choisit et prends une de ses cartes.

- Case "Vol équipement" :
- On désigne un joueur, puis on choisit et prends un de ses équipements (ne peut pas être un des items légendaire ?).

- Thème couleur ?

- Pion îcone pour reconnaître les personnages sur le plateau ?

- Protagoniste = bleu ? Neutre = jaune (gris ?) ? Antagoniste = rouge ? (Daltonien ?)

==== Cases
- 2 cases "Equipements"
- 2 cases "Consommables"
- 2 cases "Lieux"
- 2 cases "Marchands"
- 2 cases "Vol"
- 2 cases "Déplacement" (Déplacement -1 et +1)
