=== Protagoniste

  ** Alice, au pays des merveilles
    *** Curiosité : Au début de son tour, si elle le désire, Alice peut inspecter la première carte d'une des piles, à l'exception des Retournements. Elle la remet ensuite sur le dessus du paquet.
    *** Absurdité : Lorsqu'Alice atteint 1 PDB ou moins, celle-ci se transforme en Alice, de l'autre côté du miroir.
    *** Illustration :
    *** Citation : "Mais alors, dit Alice, si le monde n'a absolument aucun sens, qui nous empêche d'en inventer un ? " - Alice au pays des merveilles, Date, Lewis Carroll.
  ** Alice, de l'autre côté du miroir :
    *** Royauté : Alice ne peut être attaqué que par des personnages ayant 1 PDB ou moins.
    *** Absurdité : Lorsqu'Alice atteint 2 PDB ou plus, celle-ci se transforme en Alice, au pays des merveilles.
  ** Le petit prince
    *** Apprivoisement : lors d'une attaque visant Le petit prince, ce dernier peut imposer à l'attaquant de lancer un D6. Si le résultat est strictement inférieur à 4, l'attaque n'a pas lieu.
    *** ds

=== Antagoniste

    ** Reine de coeur :
      *** Coup d'Etat : si Alice, de l'autre côté du miroir est dans la partie, La reine de coeur perds ses pouvoirs. Elle les récupère dès lors qu'Alice, de l'autre côté du miroir n'est plus dans la partie (mort ou transformation en Alice, au pays des merveilles).
      *** Asujetissement :
      *** [["A moi !"] : utilise les sujets pour se protéger]
      *** [["A l'attaque !"] : utilise les sujets pour se protéger]
      *** YYY
    ** Capitaine Crochet
      *** Dandy : peut s'équiper de deux équipements de "Tête".
      *** Crochet : lors d'un combat, peut utiliser son crochet, rajoutant 2 points d'attaque, plutôt que son équipement "Arme".
    *** Grand méchant Loup
      *** Déguisement : peut adopter l'identité du dernier personnage qu'il vient de tuer, ne peut pas être combiné avec Dévoration.
      *** Dévoration : peut consommer le cadavre du dernier personnage qu'il vient de tuer pour récupérer deux PDB, ne peut pas être combiné avec Déguisement.
    ** Willy Wonka
      ***
* Neutre :
    ** Chat de Cheshire
      *** ds






* Tarzan
* Peter Pan, Capitaine crochet
* Mary Poppins
* Le magicien d'OZ ?
* Robin des bois
* Le livre de la jungle
* Contes grimm / perreau
* La belle et la bête
