:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:

:personnagesdir: /ressources/images/?/Personnages/


* Pouvoir
  * *Opportuniste :* à la place d'infliger des blessures lors d'une attaque, peut voler un objet équipé à la cible.
  * *Beau-parleur :* [prix réduit de 1 au marchand d'or ?]
  * Le prix chez les cases Marchands n'est que de 1.
  * Peut s'infliger une blessure pour réattaquer une seconde fois.
  * Peut choisir entre les trois premières cartes d'une pile.
  * Vous pouvez piocher les cartes de la défausse à la place de ceux des piles standards.
  * Se guérir d'une blessure au début de tous les 2 tours.
  * Inflige une blessure sur une case spécifique (marchand de sang par exemple ?)
  * Vous pouvez rejouer après avoir achever un autre personnage.
  * Désignez un autre personnage que vous, vous pouvez annuler un de ces pouvoirs au choix.
  * Contreattaquer si on est à partir d'un certain nombre de Blessures.
  * Placer le marqueur de blessure sur 3.
  * Mépris des faibles : les personnages à une blessure du _Seuil de la Mort_ ne peuvent pas vous attaquer.
  * Sacrification belliqueuse : vous subissez une blessure, la cible de votre choix, autre que vous, subit également une Blessure. Peut être fait à volonté pendant votre tour. Ne peut achever la cible ni vous tuer vous-même.

* X
  ** Les équipements n'ont aucun effets et vous ne pouvez pas consommer leur charge d'utilisation.
  ** Vous pouvez lancez les deux dés pour attaquer ou vous défendre.
* X
  ** Vous ne pouvez pas être soigné ou augmenter votre nombre de Blessures maximales de la partie.
  ** Chaque mort que vous subissez baisse votre limite de Blessures maximales de 1 et vous ramène à 0 Blessures.

* X
  ** Vous ne pouvez pas être soigné ou augmenter votre nombre de Blessures maximales de la partie.
  ** Chaque personnage que vous tué vous ramène à 0 Blessures.


* Un personnage qui se scarifie pour gagner un _Sang_.

* Un personnage qui se spécialise dans la défense ?

Liste lecture :
- Bel Ami ?
- 1984 ?
- tales of two cities

Liste personnages cools à envisager :
- Gatsby le magnifique
- Dieu
- Oskar Shell
