:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font
:nbTotal: 0
:toc:
:numbered:

:lieuxdir: /images/Lieux/

= Lieux

== Soins

=== http://harrypotter.wikia.com/wiki/Hog%27s_Head_Inn[Taverne de la Tête du Sanglier]

* Chaque _Personnage_ déjà révélée, ou se révélant, peut venir y boire une _Bièraubeurre_ et échanger / donner des cartes.

* Citation : _"Je crois que l'endroit est un peu... comment dire... un peu louche..."_, Harry Potter et l'Ordre du phénix, J.K Rowling, 2003.
* Image : {lieuxdir}hogshead.jpg

=== http://harrypotter.wikia.com/wiki/St_Mungo%27s_Hospital_for_Magical_Maladies_and_Injuries[Hôpital Ste-Mangouste]

* Interdit aux Antagonistes
* Chaque _Personnage_ au _SdM_ peut être soigné de 1 Blessure.
* Vous pouvez être soigné de 2 Blessures.

* Citation : _"Des médecins ? Tu veux dire ces Moldus cinglés qui coupent les gens en morceaux ? Non, eux, ce sont des guérisseurs."_, Harry Potter, J.K Rowling.
* Image : {lieuxdir}st_mungo.jpg

== Récupération de cartes

=== http://harrypotter.wikia.com/wiki/Madam_Malkin%27s_Robes_for_All_Occasions[Madame Guipure, prêt-à-porter pour mages et sorciers]

* Vous pouvez récupérer la première carte "Corps" ou "Tête" de la pile _Equipement_, puis mélangez la pile.

* Image : {lieuxdir}madam_malkin.jpg

=== http://harrypotter.wikia.com/wiki/Weasleys%27_Wizard_Wheezes[Boutique de Fred et Georges]

* *Goûteur dévoué :* Lancez les deux dés :
** 2 : piocher une carte _Retournement_.
** 3 : votre prochain jet de dé sera le score minimum possible.
** 4 : subissez une Blessure, puis soignez-vous 2 Blessures au début de votre prochain tour.
** 5 : vous regagnez une charge sur la compétence de _Personnage_ de votre choix.
** 6 : vous pourrez faire deux lancers de dés pour votre prochain déplacement [TODO - Meilleure idée ?].
** 7 : vous goûtez deux nouvelles dragées, quelle gourmandise !

* Citation : _"Vous avez peur de Vous-Savez-Qui ? Craignez plutôt POUSSE-RIKIKI..."_, Harry Potter et le Prince de sang-mêlé, J.K Rowling, 2005.
* Image : {lieuxdir}weasleys_wizard_wheezes.jpg

== Equipements

=== http://harrypotter.wikia.com/wiki/Borgin_and_Burkes[Barjow et Beurk]

* Vous pouvez récupérer une charge sur la compétence de l'_Equipement_ de votre choix, 2 charges si vous êtes un Antagoniste.
* Pour deux points d'_Equipement_, vous pouvez acheter la _Main de la gloire_ depuis la pile d'_Equipement_ ou _Marchand d'or_, puis mélangez la / les pile(s).

* Image : {lieuxdir}borgin_and_burkes.jpg

=== http://harrypotter.wikia.com/wiki/Gregorovitch_Zauberst%C3%A4be[Gregorovith Zauberstäbe]

* Vous pouvez récupérer une charge sur la compétence de l'_Equipement_ de votre choix.
* Vous pouvez regagner 1 charge supplémentaire pour 1 points d'_Equipement_, utilisable plusieurs fois sur plusieurs _Equipements_.
* [underline]*Assaut de Gregorovitch :*
** Vous ne pouvez tenter ceci que si vous êtes le premier à le faire.
** Attaquez Gregorovitch. Si l'attaque est supérieure à 5, emparez-vous de la _Baguette de Sureau_ dans les piles _Equipement_ et / ou _Marchand_, puis mélangez les piles fouillées.
** Les effets de ce Lieu ne vous affecteront pas jusqu'à la fin de la partie.

* Image : {lieuxdir}gregorovitch_workshop.jpg

== Evènements

=== http://harrypotter.wikia.com/wiki/Forbidden_Forest[La Forêt Interdite]

* Lancez les dés :
** *2 - Colonie d'Aragog :* si vous n'êtes pas _Aragog_, attaquer à plus de 3, 3 fois. Subissez une blessure ou défaussez un _Equipement_ par échec.
** *3 - Ford Anglia détraquée :* lancez les deux dés, si moins de 4, vous subissez une blessure. Si c'est 7, la _Ford Anglia_ vous emmène à la case adjacente de votre choix.
** *4 - Colonie centaure :* si vous êtes un Antagoniste, attaquer à plus de 5 ou lancer un d3 pour fuir. Si le résultat n'est pas 3, vous subissez une blessure, perdez un _Equipement_ et une carte de votre main. Si vous êtes Firenze, gagnez un consommable et un _Equipement_.
** *5 - Gibier :* vous pouvez attaquer, si vous faites plus de 2, guérissez-vous d'une blessure.
** *6 - Sentier mal balisé :* relancez les dés pour une autre rencontre aléatoire.
** *7 - Touffu :* lancez les deux dés, si vous faites moins de 6, vous subissez deux Blessures et perdez deux _Equipements_. Si vous n'avez pas d'_Equipement_ à perdre, perdez vos autant de cartes en main, sinon subir autant de blessures.
* Vous pouvez demander de l'aide à un autre _Personnage_ à une case de ce _Lieu_. Il peut remplir les conditions de victoire à votre place et négocier son aide, il subira aussi la défaite.

* Citation : _"Il y a des tas de bestioles là-dedans, même des loups-garous d'après ce qu'on m'a dit."_, Harry Potter à l'école des sorciers, J.K Rowling, 1997.
* Image : {lieuxdir}forbidden_forest.jpg

=== http://harrypotter.wikia.com/wiki/Azkaban[Azkaban]

* Vous pouvez attaquer un autre _Personnage_ à votre portée, en cas de victoire, il sera enfermé et ne subira pas de blessure.
* Au début de son prochain tour, il devra faire un double ou un 7 en lançant les dés pour en sortir, sinon, il perds un _Equipement_ ou une carte de sa main aléatoirement, et ainsi de suite. S'il n'a plus rien, il poursuivra son tour normalement.

* Citation : _"Ils sont enfermés dans leur propre tête, incapables d'avoir la moindre pensée agréable."_, Harry Potter et le Prisonnier d'Azkaban, J.K Rowling, 1999.
* Image : {lieuxdir}azkaban.jpg

=== http://harrypotter.wikia.com/wiki/Goblet_of_Fire[Salle de la coupe de feu]

* Chaque _Personnage_ à moins de 3 Blessures peut participer.
* il faut 3 _Personnages_ participants minimum. La coupe sélectionne aléatoirement 3 _Personnages_ parmi ceux proposés.
* Au bout de 3 tours de jeu globaux, le participant le moins blessé remporte la coupe (5 points dans le comptage final), et 3 _Equipements_ et 2 _Consommables_.
* Une fois la coupe remportée, défausser définitivement ce lieu.

* Image : {lieuxdir}goblet_of_fire.jpg

=== http://harrypotter.wikia.com/wiki/Council_of_Magical_Law[Tribunal magique]

* Vous pouvez indiquez ce que vous pensez être la quête d'un autre _Personnage_. L'accusé devra indiquer si vous dites vrai ou non, il ne peut mentir.

* Citation : _"Barry Croupton Junior !"_, Harry Potter et la Coupe de feu, J.K Rowling, 2000.
* Image : {lieuxdir}council_magical.jpg

=== http://harrypotter.wikia.com/wiki/Forest_of_Dean[Forêt de Dean]

* *Rencontre avec les rafleurs :* en commençant par le _Personnage_ qui a découvert ce lieu puis selon l'ordre de jeu, chaque _Personnage_ doit se défendre contre un groupe de rafleurs, si la défense est inférieure à 4, il perds une carte aléatoirement (de votre main ou de vos _Equipements_).

* Image : {lieuxdir}forest_of_dean.jpg

=== http://harrypotter.wikia.com/wiki/Knockturn_Alley[L'allée des embrumes]

* *Quartier très malfamé* : Vos 3 objets équipés les plus qualitatifs (dans l'ordre décroissant de qualité) vous sont retirés et sont insérés dans la pile du _Marchand d'or_.

* Citation : _"C'est un endroit très malfamé. Il ne faut surtout pas que quelqu'un te voie là-bas."_, Harry Potter et la Chambe des Secrets, J.K Rowling, 1998.
* Image : {lieuxdir}knockturn_alley.jpg

== Autres

=== http://harrypotter.wikia.com/wiki/Room_of_Requirement[La salle sur demande]

* Vous permet d'avoir l'effet de la case que vous souhaitez.

* Citation : _"Si vous devez demander, jamais vous ne saurez. Si vous savez, il suffit de demander."_, Harry Potter et les Reliques de la Mort, J.K Rowling, 2007.
* Image : {lieuxdir}room_of_requirement.jpg

=== http://harrypotter.wikia.com/wiki/Gringotts_Wizarding_Bank[Banque de Gringotts]

* Vous permet de stocker face cachées / reprendre jusqu'à deux cartes de votre main.

* Citation : _"Gringotts est l'endroit le plus sûr du monde. À part Poudlard, peut-être."_, Harry Potter à l'école des sorciers, J.K Rowling, 1997.
* Image : {lieuxdir}gringotts.jpg

=== http://harrypotter.wikia.com/wiki/The_Burrow[Le terrier]

* *Doux foyer :* Jusqu'à votre prochain tour, personne ne peut vous attaquer, vous ne pouvez attaquer personne.
* *Madame Weasley, mère au foyer :* Interdit aux Antagonistes, vous êtes soigné d'une blessure.

* Image : {lieuxdir}burrow.jpg

=== http://harrypotter.wikia.com/wiki/Diagon_Alley[Chemin de traverse]

* En commençant par celui qui a découvert le _Chemin de traverse_, puis dans l'ordre de jeu, chaque _Personnage_ peut acheter comme s'il était sur la case marchand d'or.

* Image : {lieuxdir}diagon_alley.jpg

=== http://harrypotter.wikia.com/wiki/Veil[Le voile]

* Actif pendant 2 tours de jeu globaux.
* Il ne sera pas possible de fouiller ou d'intéragir avec le corps d'un _Personnage_ mort.

* Citation : _"[...] il n'allait pas tarder à réapparaître de l'autre côté... Sirius, pourtant, ne réapparaissait pas."_, Harry Potter et l'Ordre du phénix, J.K Rowling, 2003.
* Image : {lieuxdir}veil.jpg

= Ressources

* http://harrypotter.wikia.com/wiki/Order_of_the_Phoenix
* https://en.wikipedia.org/wiki/Places_in_Harry_Potter
* http://harrypotter.wikia.com/wiki/Ministry_of_Magic
* http://harrypotter.wikia.com/wiki/Malfoy_Manor
* http://harrypotter.wikia.com/wiki/Skirmish_at_Malfoy_Manor
* http://harrypotter.wikia.com/wiki/Study_of_Ancient_Runes
* http://harrypotter.wikia.com/wiki/Fundamental_Laws_of_Magic
* http://harrypotter.wikia.com/wiki/Philosopher%27s_Stone_Chambers
* http://harrypotter.wikia.com/wiki/Mirror_of_Erised
* http://harrypotter.wikia.com/wiki/Gladrags_Wizardwear

= Idées

=== http://harrypotter.wikia.com/wiki/Twilfitt_and_Tattings[Tissard et Brodette (0.95 - TODO - Citation)]

* Vous pouvez récupérer la première carte _Equipement_ de "Corps" ou "Tête" de qualité "Rare" dans la pile, mélangez la pile après ça.

* Citation :
* Image : {lieuxdir}twilfitt_and_tattings.jpg

=== http://harrypotter.wikia.com/wiki/King%27s_Cross_Station[Gare de King's Cross (0.95 - TODO - Citation)]

* Si vous le voulez, à votre prochain tour, votre déplacement vous mènera directement à la case opposée à la votre sur le plateau.

* Citation : _"La gare est pleine de Moldus, il fallait s'y attendre."_, (TODO).
* Image : {lieuxdir}king_cross_station.jpg

=== http://harrypotter.wikia.com/wiki/Shrieking_Shack[La cabane hurlante]

** [Malus de portée quand on vous attaque dans ce lieu ?]
