:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:

= Cases

== 2 cases "Consommable" :

* Ces deux cases permettent de piocher une carte de la pile "Consommable".
* Code couleur ? (TODO)

== 2 cases "Equipement" :

* Ces deux cases permettent de piocher une carte de la pile "Equipement".
* Code couleur ? (TODO)

== 2 cases "Lieux" :

* Ces deux cases permettent de piocher la carte _Lieux_ adjacente à la case.
** Lorsque cela est fait, vous devez remettre une carte de la pile _Lieux_ face cachée de façon à ce qu'elle soit adjacente à la case.
* Code couleur ? (TODO)

== 2 cases "Marchand" :

* Cela permet de payer, via vos Blessures ou vos équipements (équipés ou dans votre main), des équipements auprès du marchand.
* Le paiement se fait au regard de tous, l'équipement reçu en revanche est face cachée et seul l'acheteur le connaît.
* Vous ne pouvez acheter les équipements une seule fois par tour (impossible par exemple d'acheter, attaquer puis racheter un équipement), mais d'autant d'équipements que vous le souhaitez / pouvez.
* Le stock de chaque marchand est déterminé de la façon suivante : taille du stock = nombre de joueurs x 2. Il vous suffit de piocher autant de cartes aléatoirement de la pile d'_Equipements_ au début de la partie.
* Bordure en couleur jaune.

=== Marchand d'or :

* Prix fixe à 3 points d'équipement.
* Un équipement commun vaut 1 point, rare 3 points, épique 5 points.
* Les légendaires ne peuvent pas être troqués. Les autres équipements troqués auprès du marchand sont défaussés définitivement (à ne pas mettre dans la pile de défausse habituelle).

=== Marchand de sang :

* Le prix fixé est de 2 Blessures.
* Vous ne pouvez acheter auprès de ce marchand si cela devrait vous tuer (si vous êtes à 1 blessures du _Seuil de la Mort_, par exemple).

== 2 cases "Larcin" :

* Une case : permet de voler une carte dans la main d'un autre joueur ciblé.
* Une case : permet de voler un objet équipé d'un autre joueur ciblé (ne peut être un objet légendaire).
* Code couleur ? (TODO)

== 2 cases "Déplacement +1 | -1" :

* Une case : vous fait reculer d'une case dans le sens où vous êtes arrivé.
* Une case : vous fait avancer d'une case dans le sens où vous êtes arrivé.
* Code couleur ? (TODO) Blanc ?
