:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:


* Vous êtes libre d'attaquer n'importe quel personnage (à l'exception de vous-même) lors de votre tour, après vous êtes déplacé (ou avoir tiré une carte retournement en cas de 7).

* Le choix de la cible est déterminé en partie par la limitation de votre portée. La portée est une statistique indiquant quelles zones autour de vous pouvez attaquer.

* Par défaut, votre portée est de 1. Cela signifie que vous pouvez attaquer votre case + les cases éloignées d'une 1 case de la vôtre, soit celles qui sont adjacentes à la votre, puisqu'il faut se déplacer de 1 case pour y accéder.

* La portée peut être augmentée ou diminuée (via les équipements, pouvoirs, etc.), néanmoins elle ne peut pas descendre en-dessous de 0, et donc vous pourrez toujours attaquer sur la case où vous vous trouvez.

* L'attaque se déroule ainsi :
** L'attaquant lance le dé à 4 faces.
** La défenseur (la cible de l'attaque) lance le dé à 3 faces.
** Les bonus des équipements, consommables, etc., s'additionne au résultat des dés.
** Si la différence est en faveur de l'attaquant, le défenseur gagne une Blessure, sinon, en cas d'égalité ou de résultat en faveur du défenseur, aucune blessure n'est infligée.
** Si l'attaque amène le défenseur à son montant maximum de Blessure qu'il peut subir, celui-ci passe dans l'état seuil de la mort. Cela signifie que la prochaine blessure de combat lui sera fatal et qu'il ne peut plus attaquer d'autres personnages. Il suffit de se soigner d'une Blessure pour quitter cet état.
** Si un personnage est tué, son assaillant a droit de récupérer un équipement de son choix, le reste de ses cartes (équipement et carte en main) sont révélées et placées dans leurs défausses respectives.
