:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:


* Vous êtes libre d'attaquer n'importe quel personnage (à l'exception de vous-même).
* Le choix de la cible est déterminé par la limitation de votre portée. La portée est une statistique indiquant quelles zones autour de vous pouvez attaquer.
* Par défaut, votre portée est de 1. Cela signifie que vous pouvez attaquer votre case + les cases éloignées de 1 case de la vôtre, soit celles qui sont adjacentes à la votre, puisqu'il faut se déplacer de 1 case pour y accéder.
* La portée peut être augmentée ou diminuée (via les équipements, pouvoirs, etc.), néanmoins elle ne peut pas descendre en-dessous de 0, et donc vous pourrez toujours attaquer sur la case où vous vous trouvez.
* Les attaques provenant d'une case à 1 de portée ou moins sont considérées au corps-à-corps, les attaques provenant d'une case à plus de 1 de portée sont considérées à distance.

* L'attaque se déroule ainsi :
** L'attaquant lance le dé à 4 faces.
** La défenseur (la cible de l'attaque) lance le dé à 3 faces.
** Les différents bonus des équipements, consommables, etc., s'additionne au résultat des dés de chaque côté.
*** Si la différence de valeur est en faveur de l'attaquant, le défenseur subit une Blessure (il devra avancer son pion d'une case sur le compteur de blessure au centre du plateau), sinon, en cas d'égalité ou de résultat en faveur du défenseur, aucune blessure n'est infligée.
*** Si l'attaque amène le défenseur à son montant maximum de Blessure qu'il peut subir, celui-ci passe dans l'état _Seuil de la Mort_. Tant qu'il est dans cet état, la prochaine blessure subie lui sera fatal et il ne peut plus attaquer d'autres personnages. Il suffit de se soigner d'une Blessure pour reculer son pion et quitter cet état.
** Si un personnage est achevé, son assaillant a droit de récupérer un objet équipé de son choix, le reste de ses cartes (équipements et cartes en main) est révélé et placé dans les défausses respectives.
