:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:


* Les points s'additionnent et se soustraient les un aux autres pour former un total. Ce total sert à déterminer le classement des joueurs à la fin de la partie.
* Si une condition pour obtenir des points se répète, vous pouvez la répéter autant de fois que nécessaire.
** Ex : Pour la condition "Vous avez tué un personnge de l'alignement adverse", si vous en avez tué 2, le calcul de ses points se produit 2 fois.

* Général
** Vous avez accompli votre quête : + 8 points
** Votre personnage est mort lors de la partie : - 5 points
** [Vous avez des Blessures restantes sur votre personnage : + 1 point par PDB (bonus d'équipement exclu)]


* [TODO]
* Alignement :
** Le meneur de jeu meurt :
  *** Si vous
** Le meneur de jeu de l'alignement allié est toujours vivant à la fin de la partie : + 2 points (1 point pour les neutres)
** Un autre personnage de l'alignement allié est toujours vivant à la fin de la partie (sauf meneur de jeu) : + 1 point
** Le meneur de jeu de l'alignement adverse a été tué : + 2 points (1 point pour les neutres)
** Vous avez tué le meneur de jeu de l'alignement adverse : + 2 points (1 point pour les neutres)
** Vous avez tué un personnage de l'alignement adverse : + 3 points (1 point pour les neutres)
** Vous avez tué un personnage de l'alignement allié : - 1 point (0 point pour les neutres)

* Vous n'avez pas utilisé de carte retournement de la partie alors que vous en possédiez une : - 1 point
* Equipements en votre possession :
  ** Légendaire : 4 points
  ** Epique : 3 points
  ** Rare : 2 points
  ** Commun : 1 points


= Retour de Thibault (TODO)
Fin de partie (POSTPONED)
Si un joueur accompli sa quête, la partie se termine à la fin du tour de jeu global.

Ajouté.

Si vous jouez avec les règles "Avancées", procédez au comptage des points et celui qui en a le plus remporte la partie. En cas d’égalité, les joueurs ex-aequo aux points sont considérés comme vainqueurs.

Même commentaire que pour l'achat de sang, mécanique qui ne doit pas être anecdotique et que chaque joueurs qui veuille s'en donner les moyens puisse orienter son jeu pour en profiter.
Ex: Si on joue en règle "avancée" là ou les objectifs de quêtes seront prépondérant, peu ou aucun joueurs auront l'occasion d'user de cette mécanique alors qu'elle est sensé "définir" cet autre mode de jeu.
De plus si un seul joueur / peu de joueurs ont un personnage qui peut gagner des points supplémentaires, les autres joueurs n'ont pas la possibilité de gagner plus de points ou de lui en faire perdre pour contrebalancer.
Ils le "tueront" au mieux comme dans un mode normal. Ils n'ont donc pas de comportement différent à adopter face à un mode qui se veut différent.

La réflexion est bonne, j'en prends note. Il y a un peu de ça dans ce premier Bloc d'Extension mais sans doute pas assez. Je pense que je reviendrai certainement dessus. A garder en tête cependant que la mort n'est pas le seul moyen commun de faire baisser les points d'autrui. Il faudra s'y pencher sérieusement une fois que le comptage de points sera conçu, je n'en suis même pas à ses balbutiements.