:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:


* Vous pouvez équiper / défausser vos objets que durant votre tour.
* Vous ne pouvez pas vous déséquiper de vos objets pour les récupérer dans votre main, mais seulement pour les défausser.
* Les équipements ont plusieurs rangs de rareté : Commun, Rare, Épique et Légendaire.
* Les personnages ne peuvent porter qu'un seul équipement Légendaire à la fois (sauf exception).
* Les équipements sont attribués à des emplacements : Tête, corps, arme et accessoire.
* On ne peut équiper un emplacement qu'avec un seul objet, sauf les accessoires qui sont limités à 2 objets.

* Lorsque vous piochez un équipement, vous pouvez : l'équiper, l'échanger / donner à un autre joueur, le défausser ou le conserver en main.
* Lorsque vous piochez un équipement Légendaire, vous devrez l'équiper ou le défausser.

* Pour bénéficier de ces effets ou de ces compétences, l'objet doit être équipé.
* Certains équipements disposent de compétences avec charges d'utilisations. Une charge est consommée par utilisation de la compétence et lorsque le compteur de charge arrive à zéro, l'objet est détruit et envoyé en défausse.
