:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:

:personnage: Personnages

= Attaque / Défense

== Attaque

* *A distance :* se dit d'une attaque à plus d'une case de distance.
* *Attaque :* action d'engager un duel envers la cible (cela peut provenir d'un _Lieu_ ou d'un _Personnage_). Pour les _Personnages_, cela se fait à l'aide de nos différents bonus d'attaque + un lancer de *d4* qui s'ajoute à ce total. Une attaque est réussie si le total de attaque est supérieur à celui de la défense. Si c'est équivalent, on dit que c'est à *égalité*.
* *Contre-attaque :* action d'attaquer immédiatement après avoir subi une attaque. Vous ne pouvez contre-attaquer une contre-attaque.
* *Corps-à-corps :* se dit d'une attaque à une case de distance ou moins.

== Défense

* *Défense :* ation de résister à une attaque. Cela se fait à l'aide de nos différents bonus de défense + un lancer de *d3* qui s'ajoute à ce total. Une défense est réussie si le total de défense est supérieur à celui de l'attaque. Si c'est équivalent, on dit que c'est à *égalité*.

= Effets

* *Loup-Garou :*
** Vous êtes obligé d'attaquer n'importe quel autre _Personnage_ à portée qui ne serait pas un *Loup-Garou*. Si plusieurs _Personnages_ sont à portée, choisissez la cible.
** +3 d'attaque et +2 de défense. Votre arme est *inactive* jusqu'à votre prochain tour.
** Si on vous attaque sans succès, vous infligez une Blessure en représailles.
** Vos attaques réussies infligent 2 Blessures.

= Equipement

* *Compagnon :* effet qui signifie que l'_Equipement_ peut être ciblé à la place du _Personnage_ lors d'une attaque et subir un certain nombre de blessures. Une fois à sa limite de Blessure atteinte, l'_Equipement_ se défausse éternellement.
* *Inactif :* état d'un _Equipement_ qui ne confère ni effets, ni compétences, ni bonus [deux noms plus distincts avec *Inutilisable*].
* *Inutilisable :* état d'un _Equipement_ qui ne confère plus effets et ne peut plus utiliser ses compétences, les bonus restent actifs [deux noms plus distincts avec *Inactif*].
* *Maîtrise :* renforcement ou ajout d'effets, de compétences ou de bonus à votre _Equipement_ si vous avez rempli certaines conditions.
** Seules les actions postérieures à l'équipement de l'objet compteront. Les effets de *Maîtrise* ne s'appliquent que tant que l'objet est équipé. Cependant, perdre cet objet puis le retrouver plus tard ne fait pas disparaître la *Maîtrise*.

= Personnages

* *Ennemi :* rapport d'adversité qui se définit par l'alignement d'un autre _Personnage_. Pour un Protagoniste, c'est l'Antagoniste (et inversement). Pour le Neutre, c'est le Protagoniste et l'Antagoniste.
* *Entravé :* état d'un _Personnage_ qui ne peut pas attaquer, se défendre, se déplacer, ou utiliser ses compétences.
* *Seuil de la Mort (SdM) :* état dans lequel où un Personnage ne peut pas attaquer et subir une Blessure supplémentaire le ferait mourir. Se soigner d'une Blessure permet de quitter cet état.

= Autres

* Un nom pour les actions que l'on ne peut tenter que si l'on est le premier à le faire ? [TODO]

* Bonus / Malus : changement brut de certaines statistiques (portée, attaque, etc.). Un bonus est décrit ainsi.
* [underline]*Compétence :* action à activer soi-même à un temps donné, une [underline]*compétence* est décrite ainsi.
* *d3 :* dé à 3 faces.
* *d4 :* dé à 4 faces.
* *Effets :* action qui se déclenche d'elle-même lorsque les conditions en sont réunies, ne nécessite pas une action explicite contrairement à la [underline]*compétence*, un *effet* est décrit ainsi.
* *Sang :* unité d'échange pour le _Marchand de Sang_ utilisée à la place des Blessures.

= Harry Potter

* [underline]*Animagus :* il s'agit d'une compétence qui vous octroie l'*effet* de l'animal transformé ou vous l'enlève si vous étiez déjà transformé. Cela passe également votre tour. Vous ne pouvez démarrer la partie avec l'effet de l'animal transformé.
* *Amendement du Ministère :* L'_Amendement du Ministère_ est une règle décidée arbitrairement parmi une la liste, plusieurs _Amendement du Ministère_ peuvent être actifs en même temps. On ne peut choisir deux fois la même règle. Les _Amendements du Ministère_ continuent d'exister même après la mort du _Personnage_ qui les a mis en place.
* *Les Reliques de la mort :* Permet d'équiper en même temps la _Cape d'Invisibilité_, la _Baguette de Sureau_ et la _Pierre de Résurrection_. Si vous avez équipé ces 3 objets durant la partie, vous devenez le Maître de la Mort. Mourir ne vous empêchera d'accomplir votre quete et ne vous fera perdre aucun point.
