:experimental:
:source-highlighter: pygments
:data-uri:
:icons: font

:toc:
:numbered:

:personnage: Personnages

* *Corps-à-corps :*
* *A distance :*
* *Maîtrise :* renforcement ou ajout de bonus supplémentaires à votre équipement si vous avez rempli certaines conditions.
** * Les conditions de maîtrise ne peuvent être remplies par des actions antérieures à l'acquisition de l'arme. Le bonus de maîtrise n'existe que tant que vous avez l'arme équipée. Cependant, perdre cette arme puis la retrouver plus tard ne fait pas disparaître la maîtrise.

* bonus : bonus de stats
* *effets :* action qui se déclenche d'elle-même lorsque les conditions en sont réunies, ne nécessite une action explicite contrairement à la compétence, un *effet*
* [underline]*compétences :* compétence à activer soi-même, une [underline]*compétence*.

* contre-attaque

* *Seuil de la Mort (SdM) :*

* inactive : pas d'effets ni de compétence, bonus toujours présents. Retourner la carte.

* *d4 :*
* *d3 :*

* Entravé : peut pas attaquer, se défendre ou se déplacer, ni utiliser ses compétences (bénéficie quand même des effets).

* *Compagnon :*

* Sang : unité d'échange pour le _Marchand de Sang_.

* Ennemi : table Antagoniste, Protagoniste, Neutre

* *défense :* défense réussie
* égalité
* attaque

 * *Loup-Garou :*
 ** Vous êtes obligé d'attaquer n'importe quel autre personnage, autre qu'un autre Loup-Garou et autre que vous, qui serait à votre portée. Si plusieurs personnages sont accessibles, choisissez la cible.
 ** +3 d'attaque et +2 de défense. Votre arme ne peut pas être utilisée et n'a aucun effet.
 ** Si vous êtes attaqué, le résultat doit forcément être à l'avantage de l'attaquant, sans quoi vous lui infliger une blessure en représailles (cela peut achever un personnage).
 ** Vos attaques réussies infligent 2 blessures (ce qui tue quelqu'un à 1 blessure du Seuil de la Mort).


==== Harry Potter

* Les reliques de la mort : Peut être équipé avec la _Cape d'Invisibilité_ et _Baguette de Sureau_.
* Si vous avez aussi équipé dans la partie la _Cape d'Invisibilité_ et la _Baguette de Sureau_, vous devenez le Maître de la Mort. Mourir ne vous fera perdre aucun point.

* Animagus : transformation pour débloqueur un effet , passe son tour, on ne démarre pas comme ça.

* Amendement du Ministère :  L'_Amendement du Ministère_ est une règle que vous décidez arbitrairement d'appliquer dans la liste ci-dessous, plusieurs _Amendement du Ministère_ peuvent être actifs en même temps. Vous ne pouvez choisir deux fois la même règle. [Les _Amendements du Ministère_ continuent d'exister même après votre mort].
